"""SYNTHETIC deeplink catalog spec (NOT OFFICIAL). Modelled on One UI Settings menus.

Each row: (entry_id, path, control, description, message, qna_description, domain, validation_key)
* path      — Settings hierarchy (used only to write gold labels and parent relations;
              the rendered catalog exposes it through `classes`, never through the URI)
* control   — screen | toggle | button | slider | list
* validation_key — toggles get a validation rule {key, boolean, equal, "true"}

Deliberate properties exercised by the tests/benchmarks:
* parent menus (Settings, Display, Battery, Device care, Apps, ...) next to exact children
* NO "Navigation bar" screen — reproduces the Appendix B dummy_positive case
* lexical distractors for "swipe"/"gesture" (Motions and gestures, Palm swipe, Home screen)
* an ambiguous pair with identical description+message (battery_legacy vs battery)
* a duplicated URI record (appended by the generator)
"""

from __future__ import annotations

CATALOG = [
    # ---------------------------------------------------------------- root / general
    ("settings", ["Settings"], "screen", "Open Settings", "Open the Settings app",
     "Open the main Settings menu to change any phone option", "General", None),
    ("connections", ["Settings", "Connections"], "screen", "Open Connections settings",
     "Manage Wi-Fi, Bluetooth, and mobile networks",
     "Change Wi-Fi, Bluetooth, airplane mode, mobile networks and data usage", "Connectivity", None),
    ("wifi", ["Settings", "Connections", "Wi-Fi"], "screen", "Open Wi-Fi settings", "Connect to Wi-Fi networks",
     "Turn Wi-Fi on or off and choose a wireless network", "Connectivity", None),
    ("bluetooth", ["Settings", "Connections", "Bluetooth"], "toggle", "Turn on Bluetooth",
     "Connect to Bluetooth devices", "Turn Bluetooth on or off and pair headphones, watches and speakers",
     "Connectivity", "bluetooth_enabled"),
    ("airplane_mode", ["Settings", "Connections", "Airplane mode"], "toggle", "Turn on Airplane mode",
     "Turn off all wireless connections", "Disable calls, Wi-Fi, Bluetooth and mobile data at once",
     "Connectivity", "airplane_mode"),
    ("mobile_hotspot", ["Settings", "Connections", "Mobile Hotspot and Tethering"], "screen",
     "Open Mobile Hotspot and Tethering", "Share your mobile data connection",
     "Share mobile data with other devices over Wi-Fi, USB or Bluetooth", "Connectivity", None),
    ("nfc", ["Settings", "Connections", "NFC and contactless payments"], "toggle", "Turn on NFC",
     "Use contactless payments", "Enable NFC to pay and share by touching devices", "Connectivity", "nfc_enabled"),
    ("data_usage", ["Settings", "Connections", "Data usage"], "screen", "Open Data usage",
     "Check mobile data usage", "See how much mobile data each app uses and set a data limit", "Connectivity", None),
    ("sounds", ["Settings", "Sounds and vibration"], "screen", "Open Sounds and vibration settings",
     "Change ringtones and volume", "Adjust volume, ringtone, notification sound and vibration pattern", "Sound", None),
    ("ringtone", ["Settings", "Sounds and vibration", "Ringtone"], "list", "Change ringtone",
     "Choose a ringtone for calls", "Pick the sound that plays for incoming calls", "Sound", None),
    ("system_sound", ["Settings", "Sounds and vibration", "System sound"], "screen", "Open System sound settings",
     "Change touch and keyboard sounds", "Turn touch interaction, screen lock and keyboard sounds on or off", "Sound", None),
    ("notifications", ["Settings", "Notifications"], "screen", "Open Notifications settings",
     "Manage app notifications", "Choose which apps can send notifications and how they appear", "Notifications", None),
    ("do_not_disturb", ["Settings", "Notifications", "Do not disturb"], "toggle", "Turn on Do not disturb",
     "Mute calls and alerts", "Silence calls, notifications and media except for allowed exceptions",
     "Notifications", "do_not_disturb"),
    # -------------------------------------------------------------------- display
    ("display", ["Settings", "Display"], "screen", "Open Display settings", "Adjust display options",
     "Change brightness, screen mode, font size, screen timeout and other display settings", "Display", None),
    ("dark_mode", ["Settings", "Display", "Dark mode"], "toggle", "Turn on Dark mode", "Use a dark colour theme",
     "Apply a dark theme to screens and apps to reduce eye strain and save battery", "Display", "dark_mode"),
    ("dark_mode_settings", ["Settings", "Display", "Dark mode settings"], "screen", "Open Dark mode settings",
     "Schedule Dark mode", "Turn on Dark mode automatically as scheduled, from sunset to sunrise or at custom times",
     "Display", None),
    ("brightness", ["Settings", "Display", "Brightness"], "slider", "Adjust screen brightness",
     "Make the screen brighter or dimmer", "Drag the brightness slider to change how bright the screen is", "Display", None),
    ("adaptive_brightness", ["Settings", "Display", "Adaptive brightness"], "toggle", "Turn on Adaptive brightness",
     "Automatically adjust brightness", "Let the phone change screen brightness based on lighting conditions and your habits",
     "Display", "adaptive_brightness"),
    ("extra_brightness", ["Settings", "Display", "Extra brightness"], "toggle", "Turn on Extra brightness",
     "Make the screen brighter than the maximum", "Increase the maximum brightness beyond the normal limit in dark or bright places",
     "Display", "extra_brightness"),
    ("motion_smoothness", ["Settings", "Display", "Motion smoothness"], "screen", "Open Motion smoothness settings",
     "Choose the screen refresh rate", "Switch between Adaptive refresh rate up to 120 Hz for smoother scrolling and Standard 60 Hz",
     "Display", None),
    ("eye_comfort", ["Settings", "Display", "Eye comfort shield"], "screen", "Open Eye comfort shield settings",
     "Reduce blue light", "Filter blue light and adjust colour temperature to reduce eye strain at night", "Display", None),
    ("screen_mode", ["Settings", "Display", "Screen mode"], "screen", "Open Screen mode settings",
     "Choose Vivid or Natural colours", "Change screen colour mode, white balance and colour tone", "Display", None),
    ("font_size", ["Settings", "Display", "Font size and style"], "screen", "Open Font size and style settings",
     "Change text size and font", "Make text bigger or smaller and change the font style", "Display", None),
    ("screen_zoom", ["Settings", "Display", "Screen zoom"], "slider", "Adjust Screen zoom",
     "Make items on screen bigger or smaller", "Zoom the screen content in or out", "Display", None),
    ("screen_resolution", ["Settings", "Display", "Screen resolution"], "list", "Change Screen resolution",
     "Choose HD+, FHD+ or WQHD+", "Lower the screen resolution to save battery or raise it for sharper images", "Display", None),
    ("full_screen_apps", ["Settings", "Display", "Camera cutout"], "screen", "Open Camera cutout settings",
     "Choose how apps show around the camera", "Hide the front camera area or show apps in full screen", "Display", None),
    ("screen_timeout", ["Settings", "Display", "Screen timeout"], "list", "Change Screen timeout",
     "Choose how long before the screen turns off", "Set how long the screen stays on when the phone is not used", "Display", None),
    ("accidental_touch", ["Settings", "Display", "Accidental touch protection"], "toggle",
     "Turn on Accidental touch protection", "Block touches in dark places",
     "Stop accidental touches when the phone is in a pocket or bag", "Display", "accidental_touch_protection"),
    ("touch_sensitivity", ["Settings", "Display", "Touch sensitivity"], "toggle", "Turn on Touch sensitivity",
     "Improve touch response with a screen protector",
     "Increase touch sensitivity so the screen responds better when you use a screen protector", "Display",
     "touch_sensitivity"),
    ("edge_panels", ["Settings", "Display", "Edge panels"], "toggle", "Turn on Edge panels",
     "Show shortcuts on the screen edge", "Swipe in from the edge of the screen to open favourite apps and tools",
     "Display", "edge_panels"),
    ("screen_saver", ["Settings", "Display", "Screen saver"], "screen", "Open Screen saver settings",
     "Show a screen saver while charging", "Display photos or colours while the phone is charging or docked", "Display", None),
    ("easy_mode", ["Settings", "Display", "Easy mode"], "toggle", "Turn on Easy mode", "Use a simpler layout",
     "Show larger icons and a simpler Home screen layout", "Display", "easy_mode"),
    # ----------------------------------------------------- lock / home / gestures
    ("lock_screen", ["Settings", "Lock screen and AOD"], "screen", "Open Lock screen settings",
     "Change lock screen options", "Change screen lock type, clock style and Always On Display", "Lock screen", None),
    ("aod", ["Settings", "Lock screen and AOD", "Always On Display"], "toggle", "Turn on Always On Display",
     "Show the clock when the screen is off", "Show time, date and notifications while the screen is off", "Lock screen",
     "always_on_display"),
    ("aod_settings", ["Settings", "Lock screen and AOD", "Always On Display settings"], "screen",
     "Open Always On Display settings", "Choose when Always On Display shows",
     "Show Always On Display only when you tap the screen, always, as scheduled or for new notifications",
     "Lock screen", None),
    ("home_screen", ["Settings", "Home screen"], "screen", "Open Home screen settings",
     "Change the Home screen layout", "Change the grid, app icon badges, and swipe down for notification panel options",
     "Home screen", None),
    ("home_swipe_notifications", ["Settings", "Home screen", "Swipe down for notification panel"], "toggle",
     "Turn on Swipe down for notification panel", "Open notifications by swiping down on the Home screen",
     "Swipe down anywhere on the Home screen to open the notification panel", "Home screen", "home_swipe_down_panel"),
    ("advanced_features", ["Settings", "Advanced features"], "screen", "Open Advanced features",
     "Try extra features", "Side button, motions and gestures, one-handed mode and screenshots", "Advanced features", None),
    ("motions_gestures", ["Settings", "Advanced features", "Motions and gestures"], "screen",
     "Open Motions and gestures settings", "Control the phone with motions",
     "Lift to wake, double tap to turn on screen, palm swipe to capture and other gestures", "Advanced features", None),
    ("palm_swipe", ["Settings", "Advanced features", "Motions and gestures", "Palm swipe to capture"], "toggle",
     "Turn on Palm swipe to capture", "Take screenshots with a hand swipe",
     "Swipe the edge of your hand across the screen to take a screenshot", "Advanced features", "palm_swipe_capture"),
    ("one_handed_mode", ["Settings", "Advanced features", "One-handed mode"], "toggle", "Turn on One-handed mode",
     "Shrink the screen for one hand", "Reduce the screen size by swiping down in the centre of the bottom edge",
     "Advanced features", "one_handed_mode"),
    ("side_button", ["Settings", "Advanced features", "Side button"], "screen", "Open Side button settings",
     "Choose what the Side button does", "Set double press and press and hold actions for the Side button",
     "Advanced features", None),
    # -------------------------------------------------------------------- battery
    ("battery", ["Settings", "Battery"], "screen", "Open Battery settings", "Check battery status",
     "View battery level, battery usage, power saving and charging options", "Battery", None),
    ("battery_legacy", ["Settings", "Device care", "Battery"], "screen", "Open Battery settings", "Check battery status",
     "Battery page inside Device care with usage and power saving", "Battery", None),
    ("battery_usage", ["Settings", "Battery", "Battery usage"], "screen", "Open Battery usage",
     "See which apps use the most battery", "View battery usage by app and system since the last full charge", "Battery", None),
    ("power_saving", ["Settings", "Battery", "Power saving"], "toggle", "Turn on Power saving",
     "Extend battery life", "Limit background network usage, sync and location to make the battery last longer",
     "Battery", "power_saving_mode"),
    ("power_saving_options", ["Settings", "Battery", "Power saving options"], "screen", "Open Power saving options",
     "Choose what Power saving limits",
     "Limit CPU speed, decrease brightness and turn off Always On Display while Power saving is on", "Battery", None),
    ("background_limits", ["Settings", "Battery", "Background usage limits"], "screen",
     "Open Background usage limits", "Manage sleeping apps",
     "Put unused apps to sleep and manage sleeping, deep sleeping and never sleeping apps", "Battery", None),
    ("put_unused_to_sleep", ["Settings", "Battery", "Background usage limits", "Put unused apps to sleep"], "toggle",
     "Turn on Put unused apps to sleep", "Stop unused apps running in the background",
     "Automatically put apps you have not used recently to sleep so they do not drain the battery", "Battery",
     "put_unused_apps_to_sleep"),
    ("deep_sleeping", ["Settings", "Battery", "Background usage limits", "Deep sleeping apps"], "screen",
     "Open Deep sleeping apps", "Choose apps that never run in the background",
     "Add apps to deep sleep so they only work when you open them", "Battery", None),
    ("never_sleeping", ["Settings", "Battery", "Background usage limits", "Never sleeping apps"], "screen",
     "Open Never sleeping apps", "Keep important apps running",
     "Choose apps that are never put to sleep so notifications arrive on time", "Battery", None),
    ("charging_settings", ["Settings", "Battery", "Charging settings"], "screen", "Open Charging settings",
     "Manage fast charging and battery protection", "Turn fast charging, super fast charging and battery protection on or off",
     "Battery", None),
    ("fast_charging", ["Settings", "Battery", "Charging settings", "Fast charging"], "toggle", "Turn on Fast charging",
     "Charge the battery faster", "Use fast charging with a compatible charger to charge the battery more quickly",
     "Battery", "fast_charging"),
    ("wireless_fast_charging", ["Settings", "Battery", "Charging settings", "Fast wireless charging"], "toggle",
     "Turn on Fast wireless charging", "Charge faster on a wireless charger",
     "Use a compatible wireless charger to charge the battery faster", "Battery", "fast_wireless_charging"),
    ("protect_battery", ["Settings", "Battery", "Charging settings", "Battery protection"], "toggle",
     "Turn on Battery protection", "Stop charging at 80 percent",
     "Limit the maximum charge to 80 percent to extend the lifespan of your battery", "Battery", "battery_protection"),
    ("adaptive_battery", ["Settings", "Battery", "More battery settings", "Adaptive battery"], "toggle",
     "Turn on Adaptive battery", "Limit battery for apps you use less",
     "Learn how you use apps and limit battery for apps you do not use often", "Battery", "adaptive_battery"),
    ("battery_percentage", ["Settings", "Battery", "More battery settings", "Show battery percentage"], "toggle",
     "Show battery percentage", "Display battery percentage in the status bar",
     "Show the remaining battery percentage next to the battery icon", "Battery", "show_battery_percentage"),
    ("battery_info", ["Settings", "Battery", "Battery information"], "screen", "Open Battery information",
     "Check battery health", "View battery capacity, charge cycles and battery status", "Battery", None),
    ("wireless_power_sharing", ["Settings", "Battery", "Wireless power sharing"], "toggle",
     "Turn on Wireless power sharing", "Charge other devices with your phone",
     "Use your phone battery to wirelessly charge earbuds, watches and other phones", "Battery",
     "wireless_power_sharing"),
    # ------------------------------------------------------ device care / performance
    ("device_care", ["Settings", "Device care"], "screen", "Open Device care", "Optimise your phone",
     "Check battery, storage, memory and device protection and optimise your phone", "Performance", None),
    ("optimize_now", ["Settings", "Device care", "Optimize now"], "button", "Optimize now",
     "Close background apps and fix issues",
     "Scan and optimise your phone by closing background apps and managing abnormal battery use", "Performance", None),
    ("memory", ["Settings", "Device care", "Memory"], "screen", "Open Memory settings", "Free up RAM",
     "Close apps running in the background to free up memory and speed up the phone", "Performance", None),
    ("storage", ["Settings", "Device care", "Storage"], "screen", "Open Storage", "Free up storage space",
     "Delete unnecessary files, duplicate images and large files to free up storage", "Performance", None),
    ("auto_optimization", ["Settings", "Device care", "Auto optimization"], "screen", "Open Auto optimization",
     "Optimise your phone automatically", "Automatically close background apps and restart the phone when needed",
     "Performance", None),
    ("auto_restart", ["Settings", "Device care", "Auto optimization", "Auto restart"], "toggle",
     "Turn on Auto restart at set times", "Restart the phone automatically",
     "Automatically restart the phone at a set time to keep it running smoothly", "Performance", "auto_restart"),
    ("performance_profile", ["Settings", "Device care", "Performance profile"], "list", "Change Performance profile",
     "Choose Light or Standard performance",
     "Balance processing speed, heat and battery life by choosing a performance profile", "Performance", None),
    ("diagnostics", ["Settings", "Device care", "Diagnostics"], "screen", "Open Diagnostics",
     "Test your phone's hardware", "Check whether the touchscreen, sensors, battery and other hardware work properly",
     "Performance", None),
    ("software_update", ["Settings", "Software update"], "screen", "Open Software update",
     "Download and install updates", "Check for the latest software update and install it", "Performance", None),
    ("general_management", ["Settings", "General management"], "screen", "Open General management",
     "Change language, keyboard and reset options", "Language, date and time, keyboard and reset settings", "General", None),
    ("reset_menu", ["Settings", "General management", "Reset"], "screen", "Open Reset options",
     "Reset settings or data", "Choose Reset all settings, Reset network settings or Factory data reset", "General", None),
    ("reset_all_settings", ["Settings", "General management", "Reset", "Reset all settings"], "button",
     "Reset all settings", "Return settings to their defaults",
     "Reset all phone settings to their defaults without deleting your data", "General", None),
    ("reset_network", ["Settings", "General management", "Reset", "Reset network settings"], "button",
     "Reset network settings", "Reset Wi-Fi, mobile data and Bluetooth",
     "Reset all network settings including Wi-Fi passwords and Bluetooth pairings", "Connectivity", None),
    ("factory_reset", ["Settings", "General management", "Reset", "Factory data reset"], "screen",
     "Open Factory data reset", "Erase all data from the phone",
     "Reset the phone to factory settings and delete all apps and personal data", "General", None),
    ("keyboard", ["Settings", "General management", "Samsung Keyboard settings"], "screen",
     "Open Samsung Keyboard settings", "Change keyboard options", "Change keyboard layout, predictive text and swipe typing",
     "General", None),
    ("date_time", ["Settings", "General management", "Date and time"], "screen", "Open Date and time settings",
     "Set the date and time", "Use automatic date and time or set them manually", "General", None),
    ("apps", ["Settings", "Apps"], "screen", "Open Apps", "Manage installed apps",
     "See installed apps, uninstall apps, and change default apps and app permissions", "Apps", None),
    ("default_apps", ["Settings", "Apps", "Choose default apps"], "screen", "Open Default apps",
     "Choose default apps", "Choose which apps open links, make calls and send messages", "Apps", None),
    ("camera_app_info", ["Settings", "Apps", "Camera"], "screen", "Open Camera app info", "Manage the Camera app",
     "Force stop the Camera app, check its storage and permissions", "Camera", None),
    ("camera_app_storage", ["Settings", "Apps", "Camera", "Storage"], "screen", "Open Camera app storage",
     "Clear Camera cache", "Clear the Camera app cache to fix crashes and errors", "Camera", None),
    ("camera_app_permissions", ["Settings", "Apps", "Camera", "Permissions"], "screen", "Open Camera app permissions",
     "Check Camera permissions", "Allow the Camera app to use the camera, microphone, location and storage", "Camera", None),
    ("developer_options", ["Settings", "Developer options"], "screen", "Open Developer options",
     "Advanced options for developers", "Change animation scale, USB debugging and other developer settings", "Performance", None),
    ("accessibility", ["Settings", "Accessibility"], "screen", "Open Accessibility settings",
     "Make the phone easier to use", "Vision, hearing, dexterity and interaction accessibility features", "Accessibility", None),
    ("remove_animations", ["Settings", "Accessibility", "Visibility enhancements", "Remove animations"], "toggle",
     "Turn on Remove animations", "Turn off screen animations",
     "Remove screen effects and animations when opening or closing apps", "Accessibility", "remove_animations"),
    ("high_contrast", ["Settings", "Accessibility", "Visibility enhancements", "High contrast fonts"], "toggle",
     "Turn on High contrast fonts", "Make text easier to read", "Add outlines to text to increase contrast", "Accessibility",
     "high_contrast_fonts"),
    ("security", ["Settings", "Security and privacy"], "screen", "Open Security and privacy settings",
     "Protect your phone and data", "Screen lock, biometrics, permissions and privacy settings", "Security", None),
    ("privacy", ["Settings", "Security and privacy", "Privacy"], "screen", "Open Privacy settings",
     "Control app access to data", "See permission usage and control camera and microphone access", "Security", None),
    ("camera_access", ["Settings", "Security and privacy", "Privacy", "Camera access"], "toggle",
     "Turn on Camera access", "Allow apps to use the camera", "Control whether apps are allowed to use the camera",
     "Camera", "camera_access"),
    ("mic_access", ["Settings", "Security and privacy", "Privacy", "Microphone access"], "toggle",
     "Turn on Microphone access", "Allow apps to use the microphone",
     "Control whether apps are allowed to use the microphone", "Security", "microphone_access"),
    ("permission_manager", ["Settings", "Security and privacy", "Privacy", "Permission manager"], "screen",
     "Open Permission manager", "Review app permissions", "See which apps can use location, camera, microphone and more",
     "Security", None),
    ("biometrics", ["Settings", "Security and privacy", "Biometrics"], "screen", "Open Biometrics settings",
     "Set up fingerprints and face recognition", "Register fingerprints or your face to unlock the phone", "Security", None),
    ("location", ["Settings", "Location"], "toggle", "Turn on Location", "Let apps use your location",
     "Allow apps and services to find where your phone is", "Location", "location_enabled"),
    ("location_services", ["Settings", "Location", "Location services"], "screen", "Open Location services",
     "Manage Wi-Fi and Bluetooth scanning", "Turn Wi-Fi scanning and Bluetooth scanning for location on or off",
     "Location", None),
    ("digital_wellbeing", ["Settings", "Digital Wellbeing and parental controls"], "screen",
     "Open Digital Wellbeing", "Check screen time", "See how much time you spend on apps and set app timers",
     "Wellbeing", None),
    ("modes_routines", ["Settings", "Modes and Routines"], "screen", "Open Modes and Routines",
     "Automate phone settings", "Create modes and routines that change settings automatically", "General", None),
    ("wallpaper", ["Settings", "Wallpaper and style"], "screen", "Open Wallpaper and style",
     "Change wallpaper and colours", "Choose wallpapers and a colour palette for the phone", "General", None),
    ("about_phone", ["Settings", "About phone"], "screen", "Open About phone", "See phone information",
     "Check the model name, software information and battery information", "General", None),
    # ---------------------------------------------------------- camera app settings
    ("camera_settings", ["Camera", "Settings"], "screen", "Open Camera settings", "Change camera options",
     "Adjust picture, video and general camera settings", "Camera", None),
    ("scene_optimizer", ["Camera", "Settings", "Scene optimizer"], "toggle", "Turn on Scene optimizer",
     "Improve photos automatically", "Adjust colour and exposure automatically to match the scene, including low light",
     "Camera", "scene_optimizer"),
    ("shot_suggestions", ["Camera", "Settings", "Shot suggestions"], "toggle", "Turn on Shot suggestions",
     "Get help framing photos", "Show guides that help you line up the best shot", "Camera", "shot_suggestions"),
    ("scan_qr", ["Camera", "Settings", "Scan QR codes"], "toggle", "Turn on Scan QR codes",
     "Detect QR codes with the camera", "Let the camera scan QR codes automatically", "Camera", "scan_qr_codes"),
    ("tracking_af", ["Camera", "Settings", "Tracking auto-focus"], "toggle", "Turn on Tracking auto-focus",
     "Keep moving subjects in focus", "Keep focus on a subject even when it moves", "Camera", "tracking_autofocus"),
    ("video_stabilization", ["Camera", "Settings", "Video stabilization"], "toggle", "Turn on Video stabilization",
     "Reduce shaky video", "Stabilise video to reduce blur caused by camera shake", "Camera", "video_stabilization"),
    ("auto_hdr", ["Camera", "Settings", "Auto HDR"], "toggle", "Turn on Auto HDR", "Capture more detail",
     "Capture more detail in bright and dark areas of photos and videos", "Camera", "auto_hdr"),
    ("picture_formats", ["Camera", "Settings", "Advanced picture options"], "screen", "Open Advanced picture options",
     "Choose HEIF or RAW formats", "Save pictures as high efficiency HEIF files or RAW copies", "Camera", None),
    ("save_selfies_as_previewed", ["Camera", "Settings", "Save selfies as previewed"], "toggle",
     "Turn on Save selfies as previewed", "Save selfies without flipping",
     "Save selfies as they appear in the preview instead of flipping them", "Camera", "save_selfies_as_previewed"),
    ("grid_lines", ["Camera", "Settings", "Grid lines"], "toggle", "Turn on Grid lines", "Show a framing grid",
     "Show guide grid lines on the viewfinder to help compose shots", "Camera", "grid_lines"),
    ("camera_storage_location", ["Camera", "Settings", "Storage location"], "list", "Change Camera storage location",
     "Save photos to the SD card or phone", "Choose whether photos and videos are saved to the phone or the SD card",
     "Camera", None),
    ("camera_shooting_methods", ["Camera", "Settings", "Shooting methods"], "screen", "Open Shooting methods",
     "Choose ways to take pictures", "Take pictures with the volume keys, voice commands, a floating shutter or palm",
     "Camera", None),
    ("camera_watermark", ["Camera", "Settings", "Watermark"], "toggle", "Turn on Watermark",
     "Add a watermark to photos", "Add the model name, date and time to the corner of photos", "Camera", "watermark"),
    ("camera_reset", ["Camera", "Settings", "Reset settings"], "button", "Reset camera settings",
     "Restore default camera settings", "Reset all camera settings to their default values", "Camera", None),
]

# Parent relations that are NOT captured by path prefixes (none currently).
EXTRA_PARENTS: dict[str, list[str]] = {}
