"""SYNTHETIC knowledge base spec (NOT OFFICIAL): canonical queries, SIIS texts and gold labels.

Every SIIS text is pre-cleaned (no URLs/images) like the PDF describes. Gold labels:
* `sections` — SIIS order; each has the rendered instruction prose and one gold action.
* gold action: name, desc (5–7 words), category, steps (atomic), target
    target  = catalog entry id (exact screen/feature)  |  "dummy" (valid Settings screen that is not
              indexed → bixby://dummy_positive)  |  None (no Settings deeplink applies)
    alts    = other entry ids that are ALSO the exact target (e.g. toggle + its screen)
    parents = entry ids that are parent menus (deeplink relevance 1)
* `order` — expected action order (critical last; Settings toggles → optimisation → reboot).
"""

from __future__ import annotations

S = "Open Settings."
RESTART = {
    "heading": "Restart your phone",
    "text": "Restarting closes apps and processes running in the background. Press and hold the Side key and the Volume down key, and then tap Restart.",
    "gold": {"key": "restart", "name": "Restart Your Phone", "desc": "It will clear temporary system glitches",
             "category": "critical", "steps": ["Press and hold the Side key and the Volume down key.", "Tap Restart."],
             "target": None},
}
UPDATE = {
    "heading": "Update the software",
    "text": "Open Settings, tap Software update, and then tap Download and install.",
    "gold": {"key": "update", "name": "Update Phone Software", "desc": "It will install the latest software fixes",
             "category": "critical", "steps": [S, "Tap Software update.", "Tap Download and install."],
             "target": "software_update", "parents": ["settings"]},
}
SAFE_MODE = {
    "heading": "Check for app problems in Safe mode",
    "text": "Press and hold the Side key and the Volume down key, and then touch and hold Power off until Safe mode appears. Tap Safe mode. If the problem stops, an app you downloaded is causing it.",
    "gold": {"key": "safe", "name": "Start Safe Mode", "desc": "It will show if apps cause problems",
             "category": "critical",
             "steps": ["Press and hold the Side key and the Volume down key.", "Touch and hold Power off until Safe mode appears.", "Tap Safe mode."],
             "target": None},
}
SERVICE = {
    "heading": "Visit a service centre",
    "text": "If the problem continues, back up your data and visit a Samsung service centre.",
    "gold": {"key": "service", "name": "Visit A Service Center", "desc": "It will get your phone professionally checked",
             "category": "manual", "steps": ["Back up your data.", "Visit a Samsung service centre."], "target": None},
}
POWER_SAVING_OFF = {
    "key": "power_off", "name": "Turn Off Power Saving", "desc": "It will stop limiting phone performance",
    "category": "auto", "steps": [S, "Tap Battery.", "Turn off Power saving."], "target": "power_saving",
    "alts": ["power_saving_options"], "parents": ["battery", "battery_legacy", "settings"],
}
CLEAN_LENS = {
    "heading": "Clean the camera lens",
    "text": "Wipe the camera lens gently with a soft, lint-free cloth.",
    "gold": {"key": "lens", "name": "Clean The Camera Lens", "desc": "It will remove smudges blocking the lens",
             "category": "manual", "steps": ["Wipe the camera lens with a soft, lint-free cloth."], "target": None},
}
FORCE_STOP_CAMERA = {
    "key": "force_stop", "name": "Force Stop the Camera App", "desc": "It will close the Camera app completely",
    "category": "auto", "steps": [S, "Tap Apps.", "Tap Camera.", "Tap Force stop.", "Tap OK."],
    "target": "camera_app_info", "parents": ["apps", "settings"],
}


def g(**kw):
    kw.setdefault("alts", [])
    kw.setdefault("parents", [])
    return kw


KB = [
    # ================================================================== DISPLAY
    {
        "id": "D01", "domain": "Display", "kind": "Troubleshooting", "topic": "Swipe Navigation",
        "title": "Swipe navigation settings", "style": "numbered",
        "query": "The mobile phone swipe navigation moves up or down instead of left or right after downloading an app.",
        "siis_title": "Swipe gestures or navigation buttons behave unexpectedly",
        "intro": "Some apps can change how navigation gestures respond, or the navigation type may have been changed. You can choose between navigation buttons and swipe gestures in the navigation bar settings.",
        "sections": [
            {"heading": "Change the navigation type",
             "text": "Open Settings and tap Display. Tap Navigation bar, and then select your preferred navigation type between Buttons and Swipe gestures. If you use swipe gestures, you can also turn on Gesture hint to show guidance lines at the bottom of the screen.",
             "gold": g(key="nav", name="Configure Navigation Bar Settings", desc="It will let you choose navigation type",
                       category="auto",
                       steps=["Navigate to and open Settings.", "Tap on Display.", "Tap on Navigation bar.", "Select your preferred navigation type between Buttons and Swipe gestures.", "Optionally toggle on Gesture hint to display guidance lines at the bottom of the screen."],
                       target="dummy", parents=["display", "settings"])},
        ],
        "outro": "Once the navigation type is set, gestures work the same way in most apps.",
        "order": ["nav"],
    },
    {
        "id": "D02", "domain": "Display", "kind": "Troubleshooting", "topic": "Screen Flicker",
        "title": "Screen flickering", "style": "numbered",
        "query": "My screen keeps flickering",
        "siis_title": "Screen flickers or blinks",
        "intro": "Screen flickering can be caused by brightness changes, the refresh rate or an app that is not optimised for your phone.",
        "sections": [
            {"heading": "Turn off Adaptive brightness",
             "text": "Adaptive brightness changes the brightness automatically and can make the screen appear to flicker in changing light. Open Settings, tap Display, and then turn off Adaptive brightness.",
             "gold": g(key="adaptive", name="Turn Off Adaptive Brightness", desc="It will stop automatic brightness changes",
                       category="auto", steps=[S, "Tap Display.", "Turn off Adaptive brightness."],
                       target="adaptive_brightness", parents=["display", "settings"])},
            {"heading": "Change the motion smoothness",
             "text": "Open Settings, tap Display, and then tap Motion smoothness. Select Standard, and then tap Apply.",
             "gold": g(key="motion", name="Change Motion Smoothness", desc="It will use a steadier refresh rate",
                       category="auto", steps=[S, "Tap Display.", "Tap Motion smoothness.", "Select Standard.", "Tap Apply."],
                       target="motion_smoothness", parents=["display", "settings"])},
            SAFE_MODE,
            UPDATE,
            {"heading": "Have the screen checked",
             "text": "If the screen still flickers, back up your data and visit a Samsung service centre.",
             "gold": dict(SERVICE["gold"])},
        ],
        "outro": "",
        "order": ["adaptive", "motion", "service", "safe", "update"],
    },
    {
        "id": "D03", "domain": "Display", "kind": "Troubleshooting", "topic": "Dim Screen",
        "title": "Dim screen", "style": "solutions",
        "query": "Screen is too dim even at full brightness",
        "siis_title": "Screen is too dark",
        "intro": "If the screen looks too dark, check the brightness settings and the features that lower brightness to save power.",
        "sections": [
            {"heading": "Adjust the brightness",
             "text": "Open Settings and tap Display. Drag the Brightness slider to the right.",
             "gold": g(key="brightness", name="Adjust Screen Brightness", desc="It will make the screen brighter",
                       category="auto", steps=[S, "Tap Display.", "Drag the Brightness slider to the right."],
                       target="brightness", parents=["display", "settings"])},
            {"heading": "Turn on Extra brightness",
             "text": "Open Settings, tap Display, and then turn on Extra brightness.",
             "gold": g(key="extra", name="Turn On Extra Brightness", desc="It will raise the maximum brightness",
                       category="auto", steps=[S, "Tap Display.", "Turn on Extra brightness."],
                       target="extra_brightness", parents=["display", "settings"])},
            {"heading": "Turn off Power saving",
             "text": "Power saving lowers the screen brightness. Open Settings, tap Battery, and then turn off Power saving.",
             "gold": dict(POWER_SAVING_OFF, desc="It will stop dimming the screen")},
            {"heading": "Turn off Eye comfort shield",
             "text": "Eye comfort shield can make the screen look darker and warmer. Open Settings, tap Display, and then tap Eye comfort shield. Turn off Eye comfort shield.",
             "gold": g(key="eye", name="Turn Off Eye Comfort Shield", desc="It will restore normal screen colours",
                       category="auto", steps=[S, "Tap Display.", "Tap Eye comfort shield.", "Turn off Eye comfort shield."],
                       target="eye_comfort", parents=["display", "settings"])},
        ],
        "outro": "",
        "order": ["brightness", "extra", "power_off", "eye"],
    },
    {
        "id": "D04", "domain": "Display", "kind": "Troubleshooting", "topic": "Screen Timeout",
        "title": "Screen turns off", "style": "numbered",
        "query": "My screen goes black after just a few seconds",
        "siis_title": "Screen turns off too quickly",
        "intro": "The screen turns off automatically after the screen timeout period to save battery.",
        "sections": [
            {"heading": "Change the screen timeout",
             "text": "Open Settings, tap Display, and then tap Screen timeout. Select a longer time, such as 2 minutes.",
             "gold": g(key="timeout", name="Change Screen Timeout", desc="It will keep the screen on longer",
                       category="auto", steps=[S, "Tap Display.", "Tap Screen timeout.", "Select a longer time, such as 2 minutes."],
                       target="screen_timeout", parents=["display", "settings"])},
            {"heading": "Turn off Power saving",
             "text": "When Power saving is on, the screen timeout is limited to 30 seconds. Open Settings, tap Battery, and then turn off Power saving.",
             "gold": dict(POWER_SAVING_OFF, desc="It will remove the 30 second limit")},
        ],
        "outro": "",
        "order": ["timeout", "power_off"],
    },
    {
        "id": "D05", "domain": "Display", "kind": "Troubleshooting", "topic": "Touchscreen Response",
        "title": "Unresponsive touchscreen", "style": "bullets",
        "query": "Touchscreen isn't responding to my taps since I put on a screen protector",
        "siis_title": "Touchscreen does not respond properly",
        "intro": "A thick or uncertified screen protector can stop the touchscreen from detecting your taps.",
        "sections": [
            {"heading": "Increase the touch sensitivity",
             "text": "Open Settings, tap Display, and then turn on Touch sensitivity. This helps the screen respond when you use a screen protector.",
             "gold": g(key="touch", name="Turn On Touch Sensitivity", desc="It will improve touch response",
                       category="auto", steps=[S, "Tap Display.", "Turn on Touch sensitivity."],
                       target="touch_sensitivity", parents=["display", "settings"])},
            {"heading": "Check the screen protector",
             "text": "Remove the screen protector if it is thick or damaged, and then clean the screen with a soft, dry cloth.",
             "gold": g(key="protector", name="Check The Screen Protector", desc="It will stop the protector blocking touches",
                       category="manual", steps=["Remove the screen protector if it is thick or damaged.", "Clean the screen with a soft, dry cloth."],
                       target=None)},
            RESTART,
        ],
        "outro": "",
        "order": ["touch", "protector", "restart"],
    },
    {
        "id": "D06", "domain": "Display", "kind": "Troubleshooting", "topic": "Screen Colour",
        "title": "Yellowish screen colours", "style": "numbered",
        "query": "The colours on my display look yellowish and warm",
        "siis_title": "Screen colours look yellow or warm",
        "intro": "Colour settings and blue light filters can make the screen look yellow.",
        "sections": [
            {"heading": "Turn off Eye comfort shield",
             "text": "Open Settings, tap Display, and then tap Eye comfort shield. Turn off Eye comfort shield.",
             "gold": g(key="eye", name="Turn Off Eye Comfort Shield", desc="It will remove the yellow tint",
                       category="auto", steps=[S, "Tap Display.", "Tap Eye comfort shield.", "Turn off Eye comfort shield."],
                       target="eye_comfort", parents=["display", "settings"])},
            {"heading": "Adjust the screen mode",
             "text": "Open Settings, tap Display, and then tap Screen mode. Select Vivid, and then drag the White balance slider towards Cool.",
             "gold": g(key="mode", name="Adjust Screen Mode", desc="It will make colours look cooler",
                       category="auto", steps=[S, "Tap Display.", "Tap Screen mode.", "Select Vivid.", "Drag the White balance slider towards Cool."],
                       target="screen_mode", parents=["display", "settings"])},
        ],
        "outro": "",
        "order": ["eye", "mode"],
    },
    {
        "id": "D07", "domain": "Display", "kind": "Troubleshooting", "topic": "Choppy Scrolling",
        "title": "Choppy scrolling", "style": "solutions",
        "query": "Scrolling feels choppy and not smooth at all",
        "siis_title": "Scrolling is not smooth",
        "intro": "Scrolling looks smoother with a higher refresh rate.",
        "sections": [
            {"heading": "Use a higher refresh rate",
             "text": "Open Settings, tap Display, and then tap Motion smoothness. Select Adaptive, and then tap Apply.",
             "gold": g(key="motion", name="Set Adaptive Motion Smoothness", desc="It will make scrolling look smoother",
                       category="auto", steps=[S, "Tap Display.", "Tap Motion smoothness.", "Select Adaptive.", "Tap Apply."],
                       target="motion_smoothness", parents=["display", "settings"])},
            {"heading": "Turn off Power saving",
             "text": "Power saving can limit the refresh rate. Open Settings, tap Battery, and then turn off Power saving.",
             "gold": dict(POWER_SAVING_OFF, desc="It will stop limiting the refresh rate")},
            {"heading": "Turn off Remove animations",
             "text": "Open Settings, tap Accessibility, and then tap Visibility enhancements. Turn off Remove animations.",
             "gold": g(key="anim", name="Turn Off Remove Animations", desc="It will restore smooth screen transitions",
                       category="auto", steps=[S, "Tap Accessibility.", "Tap Visibility enhancements.", "Turn off Remove animations."],
                       target="remove_animations", parents=["accessibility", "settings"])},
        ],
        "outro": "",
        "order": ["motion", "power_off", "anim"],
    },
    {
        "id": "D08", "domain": "Display", "kind": "Configuration", "topic": "Dark Mode",
        "title": "Dark mode setup", "style": "numbered",
        "query": "How do I turn on dark mode on my Galaxy?",
        "siis_title": "Use Dark mode",
        "intro": "Dark mode applies a dark theme that is easier on your eyes at night.",
        "sections": [
            {"heading": "Turn on Dark mode",
             "text": "Open Settings, tap Display, and then select Dark.",
             "gold": g(key="dark", name="Turn On Dark Mode", desc="It will apply a dark theme",
                       category="auto", steps=[S, "Tap Display.", "Select Dark."], target="dark_mode",
                       parents=["display", "settings"])},
            {"heading": "Schedule Dark mode",
             "text": "Open Settings, tap Display, and then tap Dark mode settings. Turn on Turn on as scheduled, and then select Sunset to sunrise or set a custom schedule.",
             "gold": g(key="schedule", name="Schedule Dark Mode", desc="It will switch themes automatically",
                       category="auto",
                       steps=[S, "Tap Display.", "Tap Dark mode settings.", "Turn on Turn on as scheduled.", "Select Sunset to sunrise or set a custom schedule."],
                       target="dark_mode_settings", parents=["display", "settings"])},
        ],
        "outro": "",
        "order": ["dark", "schedule"],
    },
    # ================================================================== BATTERY
    {
        "id": "B01", "domain": "Battery", "kind": "Troubleshooting", "topic": "Battery Drain",
        "title": "Battery fast drain", "style": "numbered",
        "query": "My phone battery dies very fast",
        "siis_title": "Battery drains quickly",
        "intro": "Battery life depends on how you use your phone. The following settings can help the battery last longer.",
        "sections": [
            {"heading": "Check the battery usage",
             "text": "Open Settings, tap Battery, and then tap Battery usage to see which apps use the most power.",
             "gold": g(key="usage", name="Check Battery Usage", desc="It will show which apps drain power",
                       category="auto", steps=[S, "Tap Battery.", "Tap Battery usage."], target="battery_usage",
                       parents=["battery", "battery_legacy", "settings"])},
            {"heading": "Put unused apps to sleep",
             "text": "Open Settings, tap Battery, and then tap Background usage limits. Turn on Put unused apps to sleep.",
             "gold": g(key="sleep", name="Put Unused Apps to Sleep", desc="It will stop unused apps draining battery",
                       category="auto", steps=[S, "Tap Battery.", "Tap Background usage limits.", "Turn on Put unused apps to sleep."],
                       target="put_unused_to_sleep", alts=["background_limits"], parents=["battery", "battery_legacy", "settings"])},
            {"heading": "Turn on Power saving",
             "text": "Open Settings, tap Battery, and then turn on Power saving.",
             "gold": g(key="power_on", name="Turn On Power Saving", desc="It will extend your battery life",
                       category="auto", steps=[S, "Tap Battery.", "Turn on Power saving."], target="power_saving",
                       alts=["power_saving_options"], parents=["battery", "battery_legacy", "settings"])},
            {"heading": "Turn off Always On Display",
             "text": "Open Settings, tap Lock screen and AOD, and then turn off Always On Display.",
             "gold": g(key="aod", name="Turn Off Always On Display", desc="It will save power with screen off",
                       category="auto", steps=[S, "Tap Lock screen and AOD.", "Turn off Always On Display."],
                       target="aod", alts=["aod_settings"], parents=["lock_screen", "settings"])},
            RESTART,
            UPDATE,
        ],
        "outro": "",
        "order": ["usage", "sleep", "power_on", "aod", "restart", "update"],
    },
    {
        "id": "B02", "domain": "Battery", "kind": "Troubleshooting", "topic": "Battery Drain After Update",
        "title": "Post-update battery drain", "style": "solutions",
        "query": "Battery started draining fast after the latest software update",
        "siis_title": "Battery drains faster after a software update",
        "intro": "After a major update, the phone optimises apps in the background, which can use more battery for a few days.",
        "sections": [
            {"heading": "Optimise your phone",
             "text": "Open Settings, tap Device care, and then tap Optimize now.",
             "gold": g(key="optimize", name="Optimize With Device Care", desc="It will close apps wasting battery",
                       category="auto", steps=[S, "Tap Device care.", "Tap Optimize now."], target="optimize_now",
                       parents=["device_care", "settings"])},
            {"heading": "Update your apps",
             "text": "Open Galaxy Store, tap Menu, and then tap Updates. Tap Update all to install the latest versions of your apps.",
             "gold": g(key="apps", name="Update Your Apps", desc="It will fix apps incompatible with update",
                       category="auto", steps=["Open Galaxy Store.", "Tap Menu.", "Tap Updates.", "Tap Update all."], target=None)},
            RESTART,
        ],
        "outro": "",
        "order": ["apps", "optimize", "restart"],
    },
    {
        "id": "B03", "domain": "Battery", "kind": "Troubleshooting", "topic": "Charging Overheating",
        "title": "Hot while charging", "style": "numbered",
        "query": "Phone gets really hot while charging",
        "siis_title": "Phone gets hot while charging",
        "intro": "It is normal for the phone to feel warm while charging, especially with fast charging. If it gets too hot, try the following.",
        "sections": [
            {"heading": "Turn off Fast charging",
             "text": "Open Settings, tap Battery, and then tap Charging settings. Turn off Fast charging.",
             "gold": g(key="fast_off", name="Turn Off Fast Charging", desc="It will reduce heat while charging",
                       category="auto", steps=[S, "Tap Battery.", "Tap Charging settings.", "Turn off Fast charging."],
                       target="fast_charging", alts=["charging_settings"], parents=["battery", "battery_legacy", "settings"])},
            {"heading": "Remove the phone case",
             "text": "Remove the phone case while charging so that heat can escape.",
             "gold": g(key="case", name="Remove The Phone Case", desc="It will let heat escape while charging",
                       category="manual", steps=["Remove the phone case while charging."], target=None)},
            {"heading": "Use the original charger",
             "text": "Use the charger and cable that came with your phone or a Samsung-certified charger.",
             "gold": g(key="charger", name="Use The Original Charger", desc="It will ensure safe, steady charging",
                       category="manual", steps=["Use the original charger and cable."], target=None)},
            RESTART,
        ],
        "outro": "",
        "order": ["fast_off", "case", "charger", "restart"],
    },
    {
        "id": "B04", "domain": "Battery", "kind": "Troubleshooting", "topic": "Charging",
        "title": "Slow charging", "style": "bullets",
        "query": "My phone won't charge or charges super slowly",
        "siis_title": "Phone does not charge or charges slowly",
        "intro": "Charging problems are often caused by the charger, the cable or dirt in the charging port.",
        "sections": [
            {"heading": "Turn on Fast charging",
             "text": "Open Settings, tap Battery, and then tap Charging settings. Turn on Fast charging.",
             "gold": g(key="fast_on", name="Turn On Fast Charging", desc="It will charge your battery faster",
                       category="auto", steps=[S, "Tap Battery.", "Tap Charging settings.", "Turn on Fast charging."],
                       target="fast_charging", alts=["charging_settings"], parents=["battery", "battery_legacy", "settings"])},
            {"heading": "Clean the charging port",
             "text": "Turn off the phone and gently clean the charging port with a soft brush.",
             "gold": g(key="port", name="Clean The Charging Port", desc="It will remove dust blocking the connection",
                       category="manual", steps=["Turn off the phone.", "Gently clean the charging port with a soft brush."],
                       target=None)},
            {"heading": "Try a different charger",
             "text": "Try a different Samsung charger and cable, and plug the charger into a different wall outlet.",
             "gold": g(key="charger", name="Try A Different Charger", desc="It will rule out a faulty charger",
                       category="manual", steps=["Try a different Samsung charger and cable.", "Plug the charger into a different wall outlet."],
                       target=None)},
            RESTART,
            {"heading": "Visit a service centre",
             "text": "If the phone still does not charge, back up your data and visit a Samsung service centre.",
             "gold": dict(SERVICE["gold"])},
        ],
        "outro": "",
        "order": ["fast_on", "port", "charger", "service", "restart"],
    },
    {
        "id": "B05", "domain": "Battery", "kind": "Configuration", "topic": "Battery Protection",
        "title": "Battery protection setup", "style": "numbered",
        "query": "How can I stop my battery from charging all the way to 100%?",
        "siis_title": "Protect the battery by limiting the charge",
        "intro": "Keeping the battery below full charge can extend its lifespan.",
        "sections": [
            {"heading": "Turn on Battery protection",
             "text": "Open Settings, tap Battery, and then tap Charging settings. Turn on Battery protection to stop charging at 80 percent.",
             "gold": g(key="protect", name="Turn On Battery Protection", desc="It will stop charging at 80 percent",
                       category="auto", steps=[S, "Tap Battery.", "Tap Charging settings.", "Turn on Battery protection."],
                       target="protect_battery", alts=["charging_settings"], parents=["battery", "battery_legacy", "settings"])},
        ],
        "outro": "",
        "order": ["protect"],
    },
    {
        "id": "B06", "domain": "Battery", "kind": "Troubleshooting", "topic": "Background Battery Usage",
        "title": "Background battery drain", "style": "solutions",
        "query": "Apps keep running in the background and eating my battery",
        "siis_title": "Apps drain the battery in the background",
        "intro": "Apps that run in the background can use battery even when you are not using them.",
        "sections": [
            {"heading": "Put unused apps to sleep",
             "text": "Open Settings, tap Battery, and then tap Background usage limits. Turn on Put unused apps to sleep.",
             "gold": g(key="sleep", name="Put Unused Apps to Sleep", desc="It will stop unused apps draining battery",
                       category="auto", steps=[S, "Tap Battery.", "Tap Background usage limits.", "Turn on Put unused apps to sleep."],
                       target="put_unused_to_sleep", alts=["background_limits"], parents=["battery", "battery_legacy", "settings"])},
            {"heading": "Add apps to deep sleep",
             "text": "Open Settings, tap Battery, tap Background usage limits, and then tap Deep sleeping apps. Tap Add, select the apps, and then tap Add.",
             "gold": g(key="deep", name="Add Apps to Deep Sleep", desc="It will block chosen apps in background",
                       category="auto",
                       steps=[S, "Tap Battery.", "Tap Background usage limits.", "Tap Deep sleeping apps.", "Tap Add.", "Select the apps.", "Tap Add."],
                       target="deep_sleeping", parents=["background_limits", "battery", "battery_legacy", "settings"])},
            {"heading": "Turn on Adaptive battery",
             "text": "Open Settings, tap Battery, and then tap More battery settings. Turn on Adaptive battery.",
             "gold": g(key="adaptive", name="Turn On Adaptive Battery", desc="It will limit rarely used apps",
                       category="auto", steps=[S, "Tap Battery.", "Tap More battery settings.", "Turn on Adaptive battery."],
                       target="adaptive_battery", parents=["battery", "battery_legacy", "settings"])},
        ],
        "outro": "",
        "order": ["sleep", "deep", "adaptive"],
    },
    {
        "id": "B07", "domain": "Battery", "kind": "Troubleshooting", "topic": "Battery Percentage",
        "title": "Battery percentage drops", "style": "numbered",
        "query": "Battery percentage suddenly drops from 40 to 5 percent",
        "siis_title": "Battery percentage changes suddenly",
        "intro": "Sudden changes in the battery percentage can be caused by software issues or battery wear.",
        "sections": [
            {"heading": "Check the battery information",
             "text": "Open Settings, tap Battery, and then tap Battery information to check the battery status.",
             "gold": g(key="info", name="Check Battery Information", desc="It will show your battery health status",
                       category="auto", steps=[S, "Tap Battery.", "Tap Battery information."], target="battery_info",
                       parents=["battery", "battery_legacy", "settings"])},
            UPDATE,
            RESTART,
            {"heading": "Have the battery checked",
             "text": "If the percentage keeps changing suddenly, visit a Samsung service centre to have the battery checked.",
             "gold": g(key="service", name="Have The Battery Checked", desc="It will get the battery professionally tested",
                       category="manual", steps=["Visit a Samsung service centre to have the battery checked."], target=None)},
        ],
        "outro": "",
        "order": ["info", "service", "restart", "update"],
    },
    {
        "id": "B08", "domain": "Battery", "kind": "Troubleshooting", "topic": "Always On Display",
        "title": "AOD battery drain", "style": "bullets",
        "query": "Always On Display is using too much battery",
        "siis_title": "Always On Display uses battery",
        "intro": "Always On Display uses a small amount of battery to show information while the screen is off.",
        "sections": [
            {"heading": "Show Always On Display only when tapped",
             "text": "Open Settings, tap Lock screen and AOD, and then tap Always On Display settings. Select Tap to show.",
             "gold": g(key="tap", name="Show AOD Only When Tapped", desc="It will show AOD only on tap",
                       category="auto", steps=[S, "Tap Lock screen and AOD.", "Tap Always On Display settings.", "Select Tap to show."],
                       target="aod_settings", parents=["lock_screen", "settings"])},
            {"heading": "Turn off Always On Display",
             "text": "Open Settings, tap Lock screen and AOD, and then turn off Always On Display.",
             "gold": g(key="off", name="Turn Off Always On Display", desc="It will save power with screen off",
                       category="auto", steps=[S, "Tap Lock screen and AOD.", "Turn off Always On Display."],
                       target="aod", parents=["lock_screen", "settings"])},
        ],
        "outro": "",
        "order": ["tap", "off"],
    },
    # =================================================================== CAMERA
    {
        "id": "C01", "domain": "Camera", "kind": "Troubleshooting", "topic": "Blurry Photos",
        "title": "Blurry camera photos", "style": "numbered",
        "query": "Camera photos come out blurry",
        "siis_title": "Photos are blurry",
        "intro": "Blurry photos are often caused by a dirty lens, camera shake or focus settings.",
        "sections": [
            CLEAN_LENS,
            {"heading": "Remove the phone case",
             "text": "Remove the phone case or cover if it blocks the camera lens.",
             "gold": g(key="case", name="Remove The Phone Case", desc="It will keep the lens unobstructed",
                       category="manual", steps=["Remove the phone case if it blocks the camera lens."], target=None)},
            {"heading": "Turn on Tracking auto-focus",
             "text": "Open the Camera app, tap Settings, and then turn on Tracking auto-focus.",
             "gold": g(key="tracking", name="Turn On Tracking Auto-Focus", desc="It will keep moving subjects in focus",
                       category="auto", steps=["Open the Camera app.", "Tap Settings.", "Turn on Tracking auto-focus."],
                       target="tracking_af", parents=["camera_settings"])},
            {"heading": "Turn on Scene optimizer",
             "text": "Open the Camera app, tap Settings, and then turn on Scene optimizer.",
             "gold": g(key="scene", name="Turn On Scene Optimizer", desc="It will adjust photos to each scene",
                       category="auto", steps=["Open the Camera app.", "Tap Settings.", "Turn on Scene optimizer."],
                       target="scene_optimizer", parents=["camera_settings"])},
            {"heading": "Reset the camera settings",
             "text": "Open the Camera app, tap Settings, and then tap Reset settings. Tap Reset to confirm.",
             "gold": g(key="reset", name="Reset Camera Settings", desc="It will restore default camera settings",
                       category="auto", steps=["Open the Camera app.", "Tap Settings.", "Tap Reset settings.", "Tap Reset."],
                       target="camera_reset", parents=["camera_settings"])},
        ],
        "outro": "",
        "order": ["tracking", "scene", "reset", "lens", "case"],
    },
    {
        "id": "C02", "domain": "Camera", "kind": "Troubleshooting", "topic": "Camera Crash",
        "title": "Camera app crashes", "style": "numbered",
        "query": "Camera app keeps crashing with a 'Camera failed' warning",
        "siis_title": "Warning: Camera failed",
        "intro": "This message appears when the Camera app stops working properly.",
        "sections": [
            {"heading": "Force stop the Camera app",
             "text": "Open Settings, tap Apps, and then tap Camera. Tap Force stop, and then tap OK.",
             "gold": dict(FORCE_STOP_CAMERA)},
            {"heading": "Clear the Camera cache",
             "text": "Open Settings, tap Apps, and then tap Camera. Tap Storage, and then tap Clear cache.",
             "gold": g(key="cache", name="Clear the Camera Cache", desc="It will remove corrupted temporary camera files",
                       category="auto", steps=[S, "Tap Apps.", "Tap Camera.", "Tap Storage.", "Tap Clear cache."],
                       target="camera_app_storage", parents=["camera_app_info", "apps", "settings"])},
            {"heading": "Check the Camera permissions",
             "text": "Open Settings, tap Apps, tap Camera, and then tap Permissions. Make sure Camera and Microphone are allowed.",
             "gold": g(key="perm", name="Check Camera Permissions", desc="It will let the camera work properly",
                       category="auto", steps=[S, "Tap Apps.", "Tap Camera.", "Tap Permissions.", "Make sure Camera and Microphone are allowed."],
                       target="camera_app_permissions", parents=["camera_app_info", "apps", "settings"])},
            RESTART,
            SAFE_MODE,
            UPDATE,
        ],
        "outro": "",
        "order": ["perm", "force_stop", "cache", "restart", "safe", "update"],
    },
    {
        "id": "C03", "domain": "Camera", "kind": "Troubleshooting", "topic": "Low Light Photos",
        "title": "Dark low-light photos", "style": "solutions",
        "query": "My photos look really dark in low light",
        "siis_title": "Photos are dark in low light",
        "intro": "The camera needs help to capture enough light in dark places.",
        "sections": [
            {"heading": "Turn on Scene optimizer",
             "text": "Scene optimizer brightens photos taken in low light. Open the Camera app, tap Settings, and then turn on Scene optimizer.",
             "gold": g(key="scene", name="Turn On Scene Optimizer", desc="It will brighten photos in low light",
                       category="auto", steps=["Open the Camera app.", "Tap Settings.", "Turn on Scene optimizer."],
                       target="scene_optimizer", parents=["camera_settings"])},
            {"heading": "Use Night mode",
             "text": "Open the Camera app, tap More, and then tap Night. Hold the phone steady while the picture is taken.",
             "gold": g(key="night", name="Use Night Mode", desc="It will capture brighter night photos",
                       category="auto", steps=["Open the Camera app.", "Tap More.", "Tap Night.", "Hold the phone steady while the picture is taken."],
                       target=None)},
            {"heading": "Turn on Auto HDR",
             "text": "Open the Camera app, tap Settings, and then turn on Auto HDR.",
             "gold": g(key="hdr", name="Turn On Auto HDR", desc="It will capture more detail in shadows",
                       category="auto", steps=["Open the Camera app.", "Tap Settings.", "Turn on Auto HDR."],
                       target="auto_hdr", parents=["camera_settings"])},
        ],
        "outro": "",
        "order": ["scene", "night", "hdr"],
    },
    {
        "id": "C04", "domain": "Camera", "kind": "Troubleshooting", "topic": "Camera Black Screen",
        "title": "Camera black screen", "style": "numbered",
        "query": "The camera just shows a black screen",
        "siis_title": "Camera shows a black screen",
        "intro": "The camera preview can stay black if camera access is blocked or the Camera app stops responding.",
        "sections": [
            {"heading": "Allow camera access",
             "text": "Open Settings, tap Security and privacy, and then tap Privacy. Turn on Camera access.",
             "gold": g(key="access", name="Turn On Camera Access", desc="It will let apps use the camera",
                       category="auto", steps=[S, "Tap Security and privacy.", "Tap Privacy.", "Turn on Camera access."],
                       target="camera_access", parents=["privacy", "security", "settings"])},
            {"heading": "Force stop the Camera app",
             "text": "Open Settings, tap Apps, and then tap Camera. Tap Force stop, and then tap OK.",
             "gold": dict(FORCE_STOP_CAMERA)},
            RESTART,
            {"heading": "Have the camera repaired",
             "text": "If the screen is still black, visit a Samsung service centre to have the camera repaired.",
             "gold": g(key="service", name="Have The Camera Repaired", desc="It will get the camera hardware checked",
                       category="manual", steps=["Visit a Samsung service centre to have the camera repaired."], target=None)},
        ],
        "outro": "",
        "order": ["access", "force_stop", "service", "restart"],
    },
    {
        "id": "C05", "domain": "Camera", "kind": "Troubleshooting", "topic": "Shaky Videos",
        "title": "Shaky videos", "style": "bullets",
        "query": "My videos are really shaky",
        "siis_title": "Videos are shaky",
        "intro": "Video stabilisation reduces the shake in videos recorded by hand.",
        "sections": [
            {"heading": "Turn on Video stabilization",
             "text": "Open the Camera app, tap Settings, and then turn on Video stabilization.",
             "gold": g(key="stab", name="Turn On Video Stabilization", desc="It will reduce shake in videos",
                       category="auto", steps=["Open the Camera app.", "Tap Settings.", "Turn on Video stabilization."],
                       target="video_stabilization", parents=["camera_settings"])},
            {"heading": "Keep the phone steady",
             "text": "Hold the phone with both hands or use a tripod while recording.",
             "gold": g(key="steady", name="Keep The Phone Steady", desc="It will prevent shaky footage",
                       category="manual", steps=["Hold the phone with both hands or use a tripod while recording."],
                       target=None)},
        ],
        "outro": "",
        "order": ["stab", "steady"],
    },
    {
        "id": "C06", "domain": "Camera", "kind": "Troubleshooting", "topic": "Camera Storage",
        "title": "Photos not saving", "style": "numbered",
        "query": "Camera won't save photos to my SD card",
        "siis_title": "Photos are not saved to the SD card",
        "intro": "Photos are saved to the phone unless you choose the SD card as the storage location.",
        "sections": [
            {"heading": "Change the storage location",
             "text": "Open the Camera app, tap Settings, and then tap Storage location. Select SD card.",
             "gold": g(key="location", name="Change Storage Location", desc="It will save photos to SD card",
                       category="auto", steps=["Open the Camera app.", "Tap Settings.", "Tap Storage location.", "Select SD card."],
                       target="camera_storage_location", parents=["camera_settings"])},
            {"heading": "Reinsert the SD card",
             "text": "Turn off the phone, remove the SD card, and then insert the SD card again.",
             "gold": g(key="sd", name="Reinsert The SD Card", desc="It will reconnect the SD card properly",
                       category="manual", steps=["Turn off the phone.", "Remove the SD card.", "Insert the SD card again."],
                       target=None)},
            {"heading": "Free up storage space",
             "text": "Open Settings, tap Device care, and then tap Storage. Delete files you no longer need.",
             "gold": g(key="storage", name="Free Up Storage Space", desc="It will make room for new photos",
                       category="auto", steps=[S, "Tap Device care.", "Tap Storage.", "Delete files you no longer need."],
                       target="storage", parents=["device_care", "settings"])},
        ],
        "outro": "",
        "order": ["location", "storage", "sd"],
    },
    {
        "id": "C07", "domain": "Camera", "kind": "Troubleshooting", "topic": "Selfie Mirroring",
        "title": "Flipped selfies", "style": "numbered",
        "query": "My selfies come out flipped like a mirror image",
        "siis_title": "Selfies are flipped",
        "intro": "By default, selfies are saved flipped compared to the preview.",
        "sections": [
            {"heading": "Save selfies as previewed",
             "text": "Open the Camera app, tap Settings, and then turn on Save selfies as previewed.",
             "gold": g(key="selfie", name="Save Selfies as Previewed", desc="It will stop selfies being flipped",
                       category="auto", steps=["Open the Camera app.", "Tap Settings.", "Turn on Save selfies as previewed."],
                       target="save_selfies_as_previewed", parents=["camera_settings"])},
        ],
        "outro": "",
        "order": ["selfie"],
    },
    {
        "id": "C08", "domain": "Camera", "kind": "Troubleshooting", "topic": "QR Code Scanning",
        "title": "QR code scanning", "style": "bullets",
        "query": "Camera isn't scanning QR codes",
        "siis_title": "Camera does not scan QR codes",
        "intro": "The camera can scan QR codes automatically when the option is turned on.",
        "sections": [
            {"heading": "Turn on Scan QR codes",
             "text": "Open the Camera app, tap Settings, and then turn on Scan QR codes.",
             "gold": g(key="qr", name="Turn On Scan QR Codes", desc="It will let the camera read codes",
                       category="auto", steps=["Open the Camera app.", "Tap Settings.", "Turn on Scan QR codes."],
                       target="scan_qr", parents=["camera_settings"])},
            CLEAN_LENS,
        ],
        "outro": "",
        "order": ["qr", "lens"],
    },
    # ============================================================== PERFORMANCE
    {
        "id": "P01", "domain": "Performance", "kind": "Troubleshooting", "topic": "Slow Performance",
        "title": "Slow after update", "style": "numbered",
        "query": "My phone got slow after the update",
        "siis_title": "Phone is slow after a software update",
        "intro": "After an update, apps are optimised in the background, which may make the phone slower for a while.",
        "sections": [
            {"heading": "Optimise with Device care",
             "text": "Open Settings, tap Device care, and then tap Optimize now.",
             "gold": g(key="optimize", name="Optimize With Device Care", desc="It will close apps slowing your phone",
                       category="auto", steps=[S, "Tap Device care.", "Tap Optimize now."], target="optimize_now",
                       parents=["device_care", "settings"])},
            {"heading": "Free up storage",
             "text": "Open Settings, tap Device care, and then tap Storage. Delete files you no longer need.",
             "gold": g(key="storage", name="Free Up Storage Space", desc="It will give the system more room",
                       category="auto", steps=[S, "Tap Device care.", "Tap Storage.", "Delete files you no longer need."],
                       target="storage", parents=["device_care", "settings"])},
            {"heading": "Update your apps",
             "text": "Open Galaxy Store, tap Menu, and then tap Updates. Tap Update all.",
             "gold": g(key="apps", name="Update Your Apps", desc="It will fix apps incompatible with update",
                       category="auto", steps=["Open Galaxy Store.", "Tap Menu.", "Tap Updates.", "Tap Update all."], target=None)},
            RESTART,
            {"heading": "Reset the phone to factory settings",
             "text": "If the phone is still slow, back up your data. Open Settings, tap General management, and then tap Reset. Tap Factory data reset.",
             "gold": g(key="factory", name="Factory Data Reset", desc="It will restore the original factory state",
                       category="critical",
                       steps=["Back up your data.", S, "Tap General management.", "Tap Reset.", "Tap Factory data reset."],
                       target="factory_reset", parents=["reset_menu", "general_management", "settings"])},
        ],
        "outro": "",
        "order": ["apps", "optimize", "storage", "restart", "factory"],
    },
    {
        "id": "P02", "domain": "Performance", "kind": "Troubleshooting", "topic": "Phone Lag",
        "title": "Laggy phone performance", "style": "solutions",
        "query": "Phone is lagging and apps take forever to open",
        "siis_title": "Phone is slow or lags",
        "intro": "Too many apps running at the same time can slow down your phone.",
        "sections": [
            {"heading": "Close apps you are not using",
             "text": "Tap the Recent apps button, and then tap Close all.",
             "gold": g(key="close", name="Close Background Apps", desc="It will free up system resources",
                       category="auto", steps=["Tap the Recent apps button.", "Tap Close all."], target=None)},
            {"heading": "Free up memory",
             "text": "Open Settings, tap Device care, and then tap Memory. Tap Clean now.",
             "gold": g(key="memory", name="Free Up Memory", desc="It will clear memory used by apps",
                       category="auto", steps=[S, "Tap Device care.", "Tap Memory.", "Tap Clean now."], target="memory",
                       parents=["device_care", "settings"])},
            {"heading": "Change the performance profile",
             "text": "Open Settings, tap Device care, and then tap Performance profile. Select Standard.",
             "gold": g(key="profile", name="Change Performance Profile", desc="It will prioritise faster processing speed",
                       category="auto", steps=[S, "Tap Device care.", "Tap Performance profile.", "Select Standard."],
                       target="performance_profile", parents=["device_care", "settings"])},
            RESTART,
        ],
        "outro": "",
        "order": ["profile", "close", "memory", "restart"],
    },
    {
        "id": "P03", "domain": "Performance", "kind": "Troubleshooting", "topic": "App Crashes",
        "title": "Apps keep crashing", "style": "numbered",
        "query": "Apps keep freezing and crashing on my phone",
        "siis_title": "Apps stop working or close unexpectedly",
        "intro": "Apps can stop working because of outdated versions, corrupted temporary files or conflicts with other apps.",
        "sections": [
            {"heading": "Update the app",
             "text": "Open Galaxy Store or Play Store and update the app.",
             "gold": g(key="update_app", name="Update The App", desc="It will install the latest app fixes",
                       category="auto", steps=["Open Galaxy Store or Play Store.", "Update the app."], target=None)},
            {"heading": "Clear the app cache",
             "text": "Open Settings, tap Apps, and then select the app. Tap Storage, and then tap Clear cache.",
             "gold": g(key="cache", name="Clear The App Cache", desc="It will remove corrupted temporary app files",
                       category="auto", steps=[S, "Tap Apps.", "Select the app.", "Tap Storage.", "Tap Clear cache."],
                       target="dummy", parents=["apps", "settings"])},
            SAFE_MODE,
        ],
        "outro": "",
        "order": ["update_app", "cache", "safe"],
    },
    {
        "id": "P04", "domain": "Performance", "kind": "Troubleshooting", "topic": "Overheating",
        "title": "Gaming overheating", "style": "numbered",
        "query": "Phone overheats while I'm gaming",
        "siis_title": "Phone gets hot while playing games",
        "intro": "Games use a lot of processing power, which makes the phone warmer.",
        "sections": [
            {"heading": "Use the Light performance profile",
             "text": "Open Settings, tap Device care, and then tap Performance profile. Select Light.",
             "gold": g(key="profile", name="Use Light Performance Profile", desc="It will reduce heat during games",
                       category="auto", steps=[S, "Tap Device care.", "Tap Performance profile.", "Select Light."],
                       target="performance_profile", parents=["device_care", "settings"])},
            {"heading": "Lower the screen brightness",
             "text": "Open Settings, tap Display, and then drag the Brightness slider to the left.",
             "gold": g(key="brightness", name="Lower Screen Brightness", desc="It will reduce power use and heat",
                       category="auto", steps=[S, "Tap Display.", "Drag the Brightness slider to the left."],
                       target="brightness", parents=["display", "settings"])},
            {"heading": "Let the phone cool down",
             "text": "Remove the phone case and stop playing until the phone cools down.",
             "gold": g(key="cool", name="Let The Phone Cool Down", desc="It will bring the temperature back down",
                       category="manual", steps=["Remove the phone case.", "Stop playing until the phone cools down."],
                       target=None)},
            UPDATE,
        ],
        "outro": "",
        "order": ["profile", "brightness", "cool", "update"],
    },
    {
        "id": "P05", "domain": "Performance", "kind": "Troubleshooting", "topic": "Storage Full",
        "title": "Full storage slowdown", "style": "bullets",
        "query": "Storage is full and my phone is running slow",
        "siis_title": "Storage is full",
        "intro": "When storage is almost full, the phone can become slow.",
        "sections": [
            {"heading": "Free up storage",
             "text": "Open Settings, tap Device care, and then tap Storage. Review the suggestions and delete files you do not need.",
             "gold": g(key="storage", name="Free Up Storage Space", desc="It will free space for the system",
                       category="auto", steps=[S, "Tap Device care.", "Tap Storage.", "Review the suggestions.", "Delete files you do not need."],
                       target="storage", parents=["device_care", "settings"])},
            {"heading": "Uninstall apps you do not use",
             "text": "Open Settings, tap Apps, select an app you do not use, and then tap Uninstall.",
             "gold": g(key="uninstall", name="Uninstall Unused Apps", desc="It will remove apps taking up space",
                       category="auto", steps=[S, "Tap Apps.", "Select an app you do not use.", "Tap Uninstall."],
                       target="dummy", parents=["apps", "settings"])},
        ],
        "outro": "",
        "order": ["uninstall", "storage"],
    },
    {
        "id": "P06", "domain": "Performance", "kind": "Troubleshooting", "topic": "Random Restarts",
        "title": "Random restarts", "style": "numbered",
        "query": "My phone restarts by itself randomly",
        "siis_title": "Phone restarts on its own",
        "intro": "The phone may restart automatically because of a scheduled restart, an app problem or a software issue.",
        "sections": [
            {"heading": "Turn off Auto restart",
             "text": "Open Settings, tap Device care, and then tap Auto optimization. Turn off Auto restart.",
             "gold": g(key="auto_restart", name="Turn Off Auto Restart", desc="It will stop scheduled automatic restarts",
                       category="auto", steps=[S, "Tap Device care.", "Tap Auto optimization.", "Turn off Auto restart."],
                       target="auto_restart", parents=["auto_optimization", "device_care", "settings"])},
            SAFE_MODE,
            UPDATE,
            {"heading": "Visit a service centre",
             "text": "If the phone keeps restarting, back up your data and visit a Samsung service centre.",
             "gold": dict(SERVICE["gold"])},
        ],
        "outro": "",
        "order": ["auto_restart", "service", "safe", "update"],
    },
    {
        "id": "P07", "domain": "Performance", "kind": "Troubleshooting", "topic": "Slow Animations",
        "title": "Slow animations", "style": "solutions",
        "query": "Animations feel slow, how do I make my phone feel faster?",
        "siis_title": "Make the phone feel faster",
        "intro": "Screen animations and the refresh rate affect how fast the phone feels.",
        "sections": [
            {"heading": "Remove animations",
             "text": "Open Settings, tap Accessibility, and then tap Visibility enhancements. Turn on Remove animations.",
             "gold": g(key="anim", name="Turn On Remove Animations", desc="It will make screen transitions instant",
                       category="auto", steps=[S, "Tap Accessibility.", "Tap Visibility enhancements.", "Turn on Remove animations."],
                       target="remove_animations", parents=["accessibility", "settings"])},
            {"heading": "Use a higher refresh rate",
             "text": "Open Settings, tap Display, and then tap Motion smoothness. Select Adaptive.",
             "gold": g(key="motion", name="Set Adaptive Motion Smoothness", desc="It will make motion look smoother",
                       category="auto", steps=[S, "Tap Display.", "Tap Motion smoothness.", "Select Adaptive."],
                       target="motion_smoothness", parents=["display", "settings"])},
        ],
        "outro": "",
        "order": ["anim", "motion"],
    },
    {
        "id": "P08", "domain": "Performance", "kind": "Troubleshooting", "topic": "Frozen Phone",
        "title": "Frozen phone", "style": "numbered",
        "query": "Phone froze and won't respond to anything",
        "siis_title": "Phone freezes or does not respond",
        "intro": "If the phone stops responding, try the following steps in order.",
        "sections": [
            {"heading": "Force restart the phone",
             "text": "Press and hold the Side key and the Volume down key for more than 7 seconds until the phone restarts.",
             "gold": g(key="force", name="Force Restart Your Phone", desc="It will restart a frozen phone",
                       category="critical", steps=["Press and hold the Side key and the Volume down key for more than 7 seconds."],
                       target=None)},
            SAFE_MODE,
            UPDATE,
            {"heading": "Reset the phone",
             "text": "If the problem continues, back up your data. Open Settings, tap General management, and then tap Reset. Tap Factory data reset.",
             "gold": g(key="factory", name="Factory Data Reset", desc="It will restore the original factory state",
                       category="critical",
                       steps=["Back up your data.", S, "Tap General management.", "Tap Reset.", "Tap Factory data reset."],
                       target="factory_reset", parents=["reset_menu", "general_management", "settings"])},
        ],
        "outro": "",
        "order": ["force", "safe", "update", "factory"],
    },
]

# Reference texts with NO viable solution (PDF §4.2.3) — used by edge-case tests, not pre-warmed.
NO_SOLUTION_DOCS = [
    {
        "id": "X01", "domain": "Performance",
        "query": "Can I use the fingerprint sensor on my phone underwater?",
        "text": "Fingerprint recognition underwater\n\nGalaxy phones do not support fingerprint recognition underwater. This is a limitation of the sensor hardware and it cannot be changed in Settings.",
    },
    {
        "id": "X02", "domain": "Display",
        "query": "Why does my screen show a notch?",
        "text": "About the front camera cutout\n\nThe front camera is placed in a small cutout at the top of the screen. The cutout is part of the phone design and is not a fault.",
    },
]

# Five reference samples (PDF §3 "samples/"): D01 reproduces Appendix B verbatim.
SAMPLE_IDS = ["D01", "B01", "C02", "P01", "D02"]
SAMPLE_VARIATIONS = {
    "D01": [
        "Ever since I installed a new app, swiping on my phone scrolls up and down instead of going left or right.",
        "Why does my phone swipe vertically when I try to swipe sideways after downloading an app?",
        "phone swipe gestures wrong direction after app install",
        "I downloaded an application yesterday and now the swipe navigation on my Galaxy moves up or down when it should go sideways.",
        "Screen navigation gestures are misbehaving after an app download; horizontal swipes register as vertical.",
        "My phone's gesture navigation got messed up by a new app and swipes go the wrong way.",
        "What should I do when swiping left or right on my phone scrolls the screen up and down instead?",
        "Swipe navigation broken after installing app.",
        "This is so annoying - I can't swipe sideways anymore since installing that app, everything just scrolls vertically.",
        "Navigation swipes on my Samsung phone respond in the wrong axis after a recent app installation.",
    ],
    "B01": [
        "My device's battery depletes much faster than expected.",
        "battery's dying crazy fast lately, what gives?",
        "battery drain fast galaxy",
        "Fast battery drain on my phone, how do I fix it?",
        "Why is my battery running out so quickly?",
        "Ugh, my phone is dead by lunchtime every single day!",
        "my batery drians so fast",
        "Hey, my phone can't even last half a day on a full charge anymore.",
        "I keep having to charge my phone because the battery goes down really quickly.",
        "Excessive battery consumption on Galaxy smartphone",
    ],
    "C02": [
        "The Camera application repeatedly terminates and displays a Camera failed message.",
        "camera keeps crashing on me, says camera failed",
        "camera failed error crash",
        "Camera app closes itself with a warning saying camera failed.",
        "How do I stop the Camera app from crashing?",
        "Seriously, every time I open the camera it says Camera failed and closes!",
        "camra app keeps crashng with camera faild",
        "So my camera app just shuts down with this Camera failed warning, any ideas?",
        "Whenever I try to take a picture, the app shows an error and quits.",
        "Camera application crash with Camera failed error dialog",
    ],
    "P01": [
        "My device has become noticeably slower since the latest software update.",
        "phone's been super sluggish since the update",
        "slow phone after software update",
        "Since updating, my Galaxy takes ages to do anything.",
        "How can I speed up my phone after the recent update?",
        "The update ruined my phone, it's so slow now!",
        "phone got slwo after the updte",
        "Hey, ever since that update everything on my phone lags.",
        "After installing the new system version, apps open much more slowly than before.",
        "Performance degradation after firmware update on Galaxy device",
    ],
    "D02": [
        "My display flickers intermittently.",
        "screen keeps flashing on and off, super weird",
        "screen flicker galaxy",
        "Flickering screen, how do I stop it?",
        "Why does my phone screen keep blinking?",
        "This flickering screen is giving me a headache, please help!",
        "my scren keeps flikering",
        "Hey, so my screen has started flickering every few seconds.",
        "The brightness on my display seems to pulse and flicker randomly.",
        "Display flicker issue on Samsung smartphone",
    ],
}
SAMPLE_SCORES = {"D01": 0.93, "B01": 0.92, "C02": 0.9, "P01": 0.9, "D02": 0.91}
# Appendix B dummy_positive text for D01.
DUMMY_TEXT = {
    ("D01", "nav"): ("Open navigation bar settings under Display", "Choose navigation type in Display settings"),
}
