"""Fill the LangAI 3.0 AI-usage disclosure form. Fields only the team can answer stay as highlighted [TO FILL] markers."""
import copy
import sys

from docx import Document
from docx.enum.text import WD_COLOR_INDEX

SRC, OUT = sys.argv[1], sys.argv[2]
d = Document(SRC)
P = d.paragraphs


def set_line(p, label, value, todo=False, keep_label_runs=1):
    """Keep the first `keep_label_runs` runs (the label), replace the rest with the value."""
    runs = p.runs
    for r in runs[keep_label_runs:]:
        r._r.getparent().remove(r._r)
    r = p.add_run((" " if label else "") + value)
    if todo:
        r.font.highlight_color = WD_COLOR_INDEX.YELLOW
    return r


def replace_all(p, text, todo=False):
    for r in p.runs[1:]:
        r._r.getparent().remove(r._r)
    if p.runs:
        p.runs[0].text = text
        if todo:
            p.runs[0].font.highlight_color = WD_COLOR_INDEX.YELLOW
    else:
        p.add_run(text)


def labelled(p, label, value):
    """'Label: value' with the label bold-free as in the form."""
    for r in p.runs[1:]:
        r._r.getparent().remove(r._r)
    p.runs[0].text = label
    p.add_run(" " + value)


# 1. Team details
set_line(P[3], True, "ResolveAI")
set_line(P[4], True, "Smart Guided Troubleshooting Engine (PRISM GenAI Hackathon 2026, Theme 2: Troubleshooting)")
set_line(P[5], True, "VITV")
set_line(P[6], True, "[TO FILL: DD-MM-YYYY]", todo=True)

# 2. Declaration
replace_all(P[9], "Did your team use any Artificial Intelligence (AI) in developing this project?  Yes")
replace_all(P[10], (
    "Yes. (a) Development: team ResolveAI analysed the problem, wrote the detailed build specification (pipeline "
    "stages, hard rules, latency and accuracy targets, hardening and traceability requirements), made the design "
    "and model decisions, integrated the official data, reviewed and tested the system and prepared the "
    "deliverables. An AI coding assistant, Claude Code (Anthropic), generated most of the implementation (code, "
    "tests, evaluation scripts and documentation drafts) from that specification, under the team's direction. "
    "(b) Inside the product: a large language model (Google Gemini gemini-3.1-flash-lite; Groq openai/gpt-oss-120b "
    "also supported) reads the SIIS reference text, and a local BAAI/bge-small-en-v1.5 embedding model powers "
    "retrieval and the semantic cache. Code, not the model, enforces every hard rule (grounding, catalog-only "
    "deeplinks, URL scrubbing, ordering, schema)."
))

# 3. Purposes
set_line(P[13], True, "Team-led: the team defined the approach (model assists, deterministic code decides) in its "
         "specification; Claude Code was used to discuss and refine design options.", keep_label_runs=2)
set_line(P[14], True, "Yes: Claude Code generated most of the Python code (FastAPI service, retrieval, extraction, "
         "mapping, validation, caching) from the team's specification; the team reviewed, ran and corrected it.")
set_line(P[15], True, "Yes: the /demo web page was generated by Claude Code to the team's requirements.")
set_line(P[16], True, "Yes: Claude Code drafted the README, reports and first version of the slides from the "
         "measured results; the team reviewed and finalised them and recorded the demo video.")
set_line(P[17], True, "Yes: Claude Code wrote the evaluation scripts; the team decided what to measure, when to "
         "re-run on the official data, and which trade-offs to accept.")
set_line(P[18], True, "Yes: Claude Code wrote the 391 offline tests; the team tested the system on its own machines "
         "and reported issues that were then fixed (HARDENING_REPORT.md).")
set_line(P[19], True, "Runtime: an LLM extracts structure from SIIS text and writes query variations; held-out "
         "test paraphrases and the synthetic development fixture were generated with LLMs (labelled as such).")

# 4. Features
FEATURES = [
    ("Query understanding and semantic cache",
     "Both",
     "Team: specified the cache behaviour, latency target (P95 <= 300 ms) and the rule that a wrong plan is worse "
     "than a miss. AI (Claude Code): generated the lexicon, canonical intent and exact + embedding cache code. "
     "The cache threshold was calibrated by a script, not by hand."),
    ("Grounded structure extraction (SIIS text to actions and steps)",
     "Both",
     "Team: defined the extraction rules (use only the SIIS text, one action per screen, imperative steps) and "
     "chose the runtime models. AI: Claude Code generated the code and prompt (app/llm/prompts.py); at run time "
     "Google Gemini gemini-3.1-flash-lite extracts with a strict JSON schema, and a grounding check removes any "
     "step not found in the SIIS text."),
    ("Deeplink mapping (hybrid BM25 + dense retrieval with exact-screen resolver)",
     "Both",
     "Team: required that URIs are only ever copied from the catalog, and directed the adaptation to the official "
     "voiceassist:// catalog. AI: Claude Code generated the retrieval and resolver code. An LLM-based mapper exists "
     "only as an ablation baseline."),
    ("Validation, safety and sequencing gates",
     "Both",
     "Team: set the rules from the schema.py contract and the problem statement (no URLs, critical actions last, "
     "manual actions without links). AI: Claude Code generated the validators; verified by adversarial tests."),
    ("Evaluation harness, metrics and reports",
     "Both",
     "Team: decided what to measure and accepted only measured numbers, including targets not met. AI: Claude Code "
     "generated the scripts, which run a real HTTP server against a live model and render metrics.md from JSON."),
    ("Demo page, presentation and video",
     "Both",
     "Team: reviewed and finalised the presentation, filled the team details and recorded the demo video "
     "(https://youtu.be/eRBRi4PisPU). AI: Claude Code generated the /demo page, the first version of the slides "
     "from the measured reports and an earlier API walkthrough video (docs/demo.webm)."),
    ("Evaluation data written for testing",
     "AI-Generated",
     "Synthetic development fixture (data/dev_fixtures, marked NOT OFFICIAL) and held-out paraphrases were "
     "generated with LLMs (Claude Code for the fixture; Gemini, qwen3.8-27b and gpt-oss-20b for paraphrases). The official starter data "
     "(data/official) was provided by the organisers and is not AI-generated by the team."),
]
tmpl = [copy.deepcopy(P[i]._p) for i in (22, 23, 24, 25)]
anchor = P[29]._p  # the "…" paragraph; features are inserted before it
for i in (22, 23, 24, 25, 26, 27, 28):
    P[i]._p.getparent().remove(P[i]._p)
from docx.text.paragraph import Paragraph

for n, (name, origin, desc) in enumerate(FEATURES, 1):
    els = [copy.deepcopy(t) for t in tmpl]
    for e in els:
        anchor.addprevious(e)
    p1, p2, p3 = (Paragraph(e, P[0]._parent) for e in els[:3])
    replace_all(p1, f"{n}. Feature Name: {name}")
    replace_all(p2, f"    Self-Generated/AI-Generated/Both: {origin}")
    replace_all(p3, f"    Description (AI tools/platform used, prompt used, output summary, modification): {desc}")
anchor.getparent().remove(anchor)

# 6. Sign-off (team only)
for p, label in ((P[36], "Name of Team Representative:"), (P[37], "Role:"), (P[38], "Signature:"), (P[39], "Date:")):
    set_line(p, True, "[TO FILL]", todo=True)

d.save(OUT)
print("saved", OUT)
