"""Fill the LangAI 3.0 AI-usage disclosure form. Fields only the team can answer stay as highlighted [TO FILL] markers."""
import copy
import sys

from docx import Document
from docx.enum.text import WD_COLOR_INDEX

SRC, OUT = sys.argv[1], sys.argv[2]
d = Document(SRC)
P = d.paragraphs


def set_line(p, label, value, todo=False, keep_label_runs=1):
    """Keep the first `keep_label_runs` runs (the label), replace the rest with the value."""
    runs = p.runs
    for r in runs[keep_label_runs:]:
        r._r.getparent().remove(r._r)
    r = p.add_run((" " if label else "") + value)
    if todo:
        r.font.highlight_color = WD_COLOR_INDEX.YELLOW
    return r


def replace_all(p, text, todo=False):
    for r in p.runs[1:]:
        r._r.getparent().remove(r._r)
    if p.runs:
        p.runs[0].text = text
        if todo:
            p.runs[0].font.highlight_color = WD_COLOR_INDEX.YELLOW
    else:
        p.add_run(text)


def labelled(p, label, value):
    """'Label: value' with the label bold-free as in the form."""
    for r in p.runs[1:]:
        r._r.getparent().remove(r._r)
    p.runs[0].text = label
    p.add_run(" " + value)


# 1. Team details
set_line(P[3], True, "[TO FILL: team name]", todo=True)
set_line(P[4], True, "Smart Guided Troubleshooting Engine (PRISM GenAI Hackathon 2026, Theme 2: Troubleshooting)")
set_line(P[5], True, "[TO FILL: college / institution]", todo=True)
set_line(P[6], True, "[TO FILL: DD-MM-YYYY]", todo=True)

# 2. Declaration
replace_all(P[9], "Did your team use any Artificial Intelligence (AI) in developing this project?  Yes")
replace_all(P[10], (
    "Yes. AI was used in two ways. (a) Development: the code, tests, evaluation scripts, documentation, synthetic "
    "development data, presentation and demo video were produced with Claude Code (Anthropic's agentic coding "
    "assistant), working under the team's direction and specification; the team reviewed the work, ran it and "
    "made the design decisions. (b) Inside the product: a large language model (Groq openai/gpt-oss-120b for "
    "extraction, openai/gpt-oss-20b for query variations; Google Gemini also supported) reads the SIIS reference "
    "text, and a local BAAI/bge-small-en-v1.5 embedding model powers retrieval and the semantic cache. Code, "
    "not the model, enforces every hard rule (grounding, catalog-only deeplinks, URL scrubbing, ordering, schema)."
))

# 3. Purposes
set_line(P[13], True, "Yes: Claude Code proposed the pipeline design (deterministic gates around a "
         "model-assisted extraction step) from the team's problem statement; the team chose the approach.", keep_label_runs=2)
set_line(P[14], True, "Yes: most of the Python code (FastAPI service, retrieval, extraction, mapping, validation, "
         "caching) was generated by Claude Code and reviewed by the team.")
set_line(P[15], True, "Yes: the /demo web page was generated by Claude Code.")
set_line(P[16], True, "Yes: README, metrics report, hardening report, traceability matrix, this presentation and the "
         "demo video were drafted by Claude Code; every number in them is rendered from measured reports.")
set_line(P[17], True, "Yes: evaluation scripts written with Claude Code measure accuracy, latency, cost and cache hit "
         "rate against a live model; the analysis of the results was AI-assisted.")
set_line(P[18], True, "Yes: Claude Code wrote 390 offline tests (unit, integration, regression, adversarial) and "
         "fixed the issues found by a hostile review (HARDENING_REPORT.md).")
set_line(P[19], True, "Runtime: an LLM extracts structure from SIIS text and writes query variations; held-out "
         "test paraphrases and the synthetic development fixture were generated with LLMs (labelled as such).")

# 4. Features
FEATURES = [
    ("Query understanding and semantic cache",
     "Both",
     "Claude Code (Anthropic) generated the code from the team's specification prompt (problem statement, latency "
     "and accuracy targets). Output: domain lexicon, canonical intent, exact + embedding cache with concept and "
     "qualifier gates. The team set the targets; the cache threshold was calibrated by a script, not by hand."),
    ("Grounded structure extraction (SIIS text to actions and steps)",
     "Both",
     "Runtime LLM: Groq openai/gpt-oss-120b with a strict JSON schema. Prompt: the extraction rules in "
     "app/llm/prompts.py (use only the SOURCE, one action per screen, imperative steps). Code written by Claude Code; "
     "a deterministic grounding check removes any step not found in the SIIS text."),
    ("Deeplink mapping (hybrid BM25 + dense retrieval with exact-screen resolver)",
     "Both",
     "Code generated by Claude Code. No LLM picks URIs: the URI is always copied from the catalog. An LLM-based "
     "mapper exists only as an ablation baseline. Adapted by the team's direction to the official catalog format."),
    ("Validation, safety and sequencing gates",
     "Both",
     "Code generated by Claude Code from the schema.py contract and the hackathon rules: schema validation, business "
     "rules, URL and prompt-injection scrubbing, critical-last ordering. Verified by adversarial tests."),
    ("Evaluation harness, metrics and reports",
     "Both",
     "Scripts generated by Claude Code; they run the real HTTP server against a live model and render metrics.md "
     "from JSON. No figure was typed by hand."),
    ("Demo page, presentation and video",
     "Both",
     "Generated with Claude Code (HTML page, python-pptx/pptxgenjs deck, Playwright-recorded browser video) "
     "from the measured reports; team details are filled in by the team."),
    ("Evaluation data written for testing",
     "AI-Generated",
     "Synthetic development fixture (data/dev_fixtures, marked NOT OFFICIAL) and held-out paraphrases were "
     "generated with LLMs (Claude Code for the fixture; Gemini, qwen3.8-27b and gpt-oss-20b for paraphrases). The official starter data "
     "(data/official) was provided by the organisers and is not AI-generated by the team."),
]
tmpl = [copy.deepcopy(P[i]._p) for i in (22, 23, 24, 25)]
anchor = P[29]._p  # the "…" paragraph; features are inserted before it
for i in (22, 23, 24, 25, 26, 27, 28):
    P[i]._p.getparent().remove(P[i]._p)
from docx.text.paragraph import Paragraph

for n, (name, origin, desc) in enumerate(FEATURES, 1):
    els = [copy.deepcopy(t) for t in tmpl]
    for e in els:
        anchor.addprevious(e)
    p1, p2, p3 = (Paragraph(e, P[0]._parent) for e in els[:3])
    replace_all(p1, f"{n}. Feature Name: {name}")
    replace_all(p2, f"    Self-Generated/AI-Generated/Both: {origin}")
    replace_all(p3, f"    Description (AI tools/platform used, prompt used, output summary, modification): {desc}")
anchor.getparent().remove(anchor)

# 6. Sign-off (team only)
for p, label in ((P[36], "Name of Team Representative:"), (P[37], "Role:"), (P[38], "Signature:"), (P[39], "Date:")):
    set_line(p, True, "[TO FILL]", todo=True)

d.save(OUT)
print("saved", OUT)
