#!/usr/bin/env python3
"""Render the SYNTHETIC dev fixture dataset (NOT OFFICIAL) into data/dev_fixtures/.

Deterministic: running it twice produces byte-identical files. The official starter assets
(queries.json, siis_responses.json, deeplinks.json, samples/) go in data/official/ instead.

    python scripts/generate_dev_fixtures.py
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from dev_fixture_spec.catalog_spec import CATALOG  # noqa: E402
from dev_fixture_spec.eval_spec import (  # noqa: E402
    EDGE_CASES,
    NEGATIVES_BORDERLINE,
    NEGATIVES_UNRELATED,
    PARAPHRASES,
)
from dev_fixture_spec.kb_spec import (  # noqa: E402
    DUMMY_TEXT,
    KB,
    NO_SOLUTION_DOCS,
    SAMPLE_IDS,
    SAMPLE_SCORES,
    SAMPLE_VARIATIONS,
)

OUT = ROOT / "data" / "dev_fixtures"
NOTICE = "SYNTHETIC DEV FIXTURE — NOT OFFICIAL SAMSUNG DATA. Generated by scripts/generate_dev_fixtures.py."
DUMMY = "bixby://dummy_positive"
APPENDIX_B_META = {"latency_ms": 212, "cache_hit": True, "model": "gpt-4o-mini", "cost_usd": 0.0}


def masked(entry_id: str, kind: str = "act") -> str:
    return f"bixby://masked/{kind}/" + hashlib.sha256(f"dev:{kind}:{entry_id}".encode()).hexdigest()[:12]


def dump(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def build_catalog():
    records, meta = [], {}
    paths = {row[0]: row[1] for row in CATALOG}
    for entry_id, path, control, desc, msg, qna, domain, vkey in CATALOG:
        rec = {
            "deeplink": masked(entry_id),
            "description": desc,
            "message": msg,
            "qna_description": qna,
            "classes": {"category": domain},
            "originalType": control,
        }
        if vkey:
            rec["validation"] = {
                "deeplink": masked(entry_id, "val"),
                "key": vkey,
                "resultType": "boolean",
                "condition": "equal",
                "value": "true",
            }
        records.append(rec)
        parents = [pid for pid, ppath in paths.items() if len(ppath) < len(path) and path[: len(ppath)] == ppath]
        meta[entry_id] = {"uri": rec["deeplink"], "path": path, "control": control, "parents": parents,
                          "validation_uri": rec.get("validation", {}).get("deeplink")}
    # One duplicated URI record (identical metadata) to exercise duplicate detection.
    dup = dict(next(r for r in records if r["deeplink"] == masked("battery")))
    records.append(dup)
    return records, meta


def render_siis(item) -> str:
    lines = [item["siis_title"], "", item["intro"], ""]
    for i, sec in enumerate(item["sections"], start=1):
        if item["style"] == "numbered":
            lines += [f"{i}. {sec['heading']}", sec["text"], ""]
        elif item["style"] == "solutions":
            lines += [f"Solution {i}: {sec['heading']}", sec["text"], ""]
        else:
            lines += [f"- {sec['heading']}: {sec['text']}", ""]
    if item.get("outro"):
        lines += [item["outro"], ""]
    return "\n".join(lines).strip() + "\n"


def wants_off(steps) -> bool:
    return bool(re.search(r"(?i)\bturn\s+off\b|\bdisable\b|\bswitch\s+off\b", " ".join(steps)))


def gold_actions(item, meta):
    by_key = {sec["gold"]["key"]: sec["gold"] for sec in item["sections"]}
    missing = set(item["order"]) ^ set(by_key)
    if missing:
        raise SystemExit(f"{item['id']}: order/sections mismatch {missing}")
    out = []
    for key in item["order"]:
        gld = by_key[key]
        tgt = gld.get("target")
        out.append({
            "key": key,
            "name": gld["name"],
            "desc": gld["desc"],
            "category": gld["category"],
            "steps": gld["steps"],
            "target": tgt,
            "target_uri": DUMMY if tgt == "dummy" else (meta[tgt]["uri"] if tgt else None),
            "alt_uris": [meta[a]["uri"] for a in gld.get("alts", [])],
            "parent_uris": [meta[p]["uri"] for p in gld.get("parents", [])],
        })
    return out


def deeplink_obj(item, action, records_by_uri, meta):
    if action["category"] == "manual" or not action["target"]:
        return None, None
    if action["target"] == "dummy":
        desc, msg = DUMMY_TEXT.get((item["id"], action["key"]), (f"Open {action['name'].lower()} screen", ""))
        dl = {"deeplink": DUMMY, "description": desc}
        if msg:
            dl["message"] = msg
        return dl, None
    rec = records_by_uri[action["target_uri"]]
    dl = {k: rec[k] for k in ("deeplink", "description", "message", "classes", "originalType") if k in rec}
    val = rec.get("validation")
    vdl = dict(val) if val and not wants_off(action["steps"]) else None
    return dl, vdl


def build_sample(item, gold, records_by_uri, meta, siis_text):
    actions = []
    for a in gold:
        dl, vdl = deeplink_obj(item, a, records_by_uri, meta)
        actions.append({
            "actionName": a["name"],
            "description": a["desc"],
            "category": a["category"],
            "stepGroups": [{"steps": a["steps"], "actionableDeeplink": dl, "validationDeeplink": vdl}],
        })
    envelope = {
        "query": item["query"],
        "query_variations": SAMPLE_VARIATIONS[item["id"]],
        "response": {"contexts": [{
            "goal": f"Follow these steps to perform this {item['topic']} {item['kind']}",
            "title": item["title"],
            "score": SAMPLE_SCORES[item["id"]],
            "actions": actions,
        }]},
        "meta": APPENDIX_B_META if item["id"] == "D01" else
        {"latency_ms": 1800, "cache_hit": False, "model": "reference-gold", "cost_usd": 0.0},
    }
    return {"_notice": NOTICE, "input": {"query": item["query"], "siis_response": siis_text}, "output": envelope}


def main() -> int:
    records, meta = build_catalog()
    records_by_uri = {}
    for r in records:
        records_by_uri.setdefault(r["deeplink"], r)
    queries, siis, gold = [], [], {}
    samples = {}
    for item in KB:
        text = render_siis(item)
        queries.append({"id": item["id"], "domain": item["domain"], "query": item["query"]})
        siis.append({"id": f"S-{item['id']}", "query_id": item["id"], "domain": item["domain"],
                     "title": item["siis_title"], "siis_response": text})
        ga = gold_actions(item, meta)
        gold[item["id"]] = {"domain": item["domain"], "kind": item["kind"], "topic": item["topic"],
                            "title": item["title"], "query": item["query"], "actions": ga}
        if item["id"] in SAMPLE_IDS:
            samples[item["id"]] = build_sample(item, ga, records_by_uri, meta, text)

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "README.md").write_text(
        f"# {NOTICE}\n\nThese files stand in for the official starter assets, which were not supplied.\n"
        "They are hand-authored from general One UI knowledge and the PDF's worked example; they are\n"
        "NOT Samsung SIIS content and NOT the official ~575-entry catalog. Every metric computed on them is\n"
        "labelled `dev_fixtures` in metrics.md. Put the official files in `data/official/` to replace them.\n",
        encoding="utf-8",
    )
    dump(OUT / "deeplinks.json", records)
    dump(OUT / "queries.json", queries)
    dump(OUT / "siis_responses.json", siis)
    for i, sid in enumerate(SAMPLE_IDS, start=1):
        dump(OUT / "samples" / f"sample_{i:02d}_{sid}.json", samples[sid])
    dump(OUT / "eval" / "gold.json", {"_notice": NOTICE, "queries": gold})
    dump(OUT / "eval" / "catalog_meta.json", {"_notice": NOTICE, "entries": meta})
    calib = [{"query_id": q, "text": t} for q, ps in PARAPHRASES.items() for t in ps[:2]]
    test = [{"query_id": q, "text": t} for q, ps in PARAPHRASES.items() for t in ps[2:]]
    dump(OUT / "eval" / "paraphrases.json", {"_notice": NOTICE, "calibration": calib, "test": test})
    dump(OUT / "eval" / "negatives.json", {"_notice": NOTICE, "unrelated": NEGATIVES_UNRELATED,
                                           "borderline": NEGATIVES_BORDERLINE})
    no_sol = {d["id"]: d for d in NO_SOLUTION_DOCS}
    edges = []
    for e in EDGE_CASES:
        e = dict(e)
        if "siis_doc" in e:
            e["siis"] = no_sol[e.pop("siis_doc")]["text"]
        edges.append(e)
    dump(OUT / "eval" / "edge_cases.json", {"_notice": NOTICE, "cases": edges})
    dump(OUT / "eval" / "no_solution_docs.json", {"_notice": NOTICE, "docs": NO_SOLUTION_DOCS})

    # Self-check: the reference samples must satisfy every contract gate.
    from app.catalog.loaders import parse_catalog
    from app.catalog.registry import CatalogRegistry
    from app.validation.business_rules import validate_envelope

    entries, issues = parse_catalog(json.loads((OUT / "deeplinks.json").read_text()), "deeplinks.json")
    reg = CatalogRegistry(entries, issues=issues)
    bad = 0
    for sid, s in samples.items():
        rep = validate_envelope(s["output"], reg)
        if not rep.ok:
            bad += 1
            print(f"sample {sid} violates the contract: {rep.summary()}")
    print(f"catalog records={len(records)} unique={len(reg)} queries={len(queries)} siis={len(siis)} "
          f"samples={len(samples)} paraphrases={len(calib)}+{len(test)} negatives="
          f"{len(NEGATIVES_UNRELATED)}+{len(NEGATIVES_BORDERLINE)} edge_cases={len(edges)}")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
